[package]
name = "append_squashfs_overlay"
version = "0.1.0"
authors = ["Jeongik Cha <jeongik@google.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.5.0", features = [ "derive", "error-context", "help", "std", "usage" ] }
