sh_library(
    name = "build-debs-with-docker",
    visibility = ["//visibility:public"],
    srcs = ["build-debs-with-docker.sh"],
)

sh_library(
    name = "build-hostpkg",
    visibility = ["//visibility:public"],
    srcs = ["build-hostpkg.sh"],
)

sh_library(
    name = "dockerfile",
    visibility = ["//visibility:public"],
    srcs = ["Dockerfile.debbld"],
)
