# Docker image for running CF instances in the server.
# Docker image includes HO(Host Orchestrator) inside,
# so it could execute CF instance with API in HO.

ARG BUILD_OPTION=prod


FROM debian:12 AS runner-base

# Expose Operator Port (HTTP:1080, HTTPS:1443)
EXPOSE 1080 1443
# Expose HO(Host Orchestrator) Port (HTTP:2080, HTTPS:2443)
EXPOSE 2080 2443
# Expose WebRTC Port
EXPOSE 15550-15560
# Expose ADB Port
# Corresponding ADB port for CF instance is, 6520+instance_num-1.
EXPOSE 6520-6620
# to make sure this file always exist
RUN touch /.dockerenv

USER root
WORKDIR /root
RUN set -x
RUN apt update
RUN apt install -y --no-install-recommends \
    ca-certificates \
    curl \
    mesa-utils \
    nginx \
    sudo
RUN update-ca-certificates

COPY ./container/guest/run_services.sh /root/
RUN chmod +x /root/run_services.sh


FROM runner-base AS runner-dev

COPY cuttlefish-*.deb /root/debian/
RUN apt install -y --no-install-recommends -f \
    /root/debian/cuttlefish-base_*.deb \
    /root/debian/cuttlefish-user_*.deb \
    /root/debian/cuttlefish-orchestration_*.deb


FROM runner-base AS runner-prod

ARG REPO
RUN apt install -y --no-install-recommends gnupg
RUN curl https://us-apt.pkg.dev/doc/repo-signing-key.gpg | apt-key add -
RUN echo "deb https://us-apt.pkg.dev/projects/android-cuttlefish-artifacts $REPO main" \
    | tee -a /etc/apt/sources.list.d/artifact-registry.list
RUN apt update
RUN apt install -y --no-install-recommends \
    cuttlefish-base \
    cuttlefish-user \
    cuttlefish-orchestration


FROM runner-${BUILD_OPTION} AS runner

RUN usermod -aG kvm root
RUN usermod -aG cvdnetwork root
ENTRYPOINT ["/root/run_services.sh"]
