sh_library(
    name = "dockerfile",
    visibility = ["//visibility:public"],
    srcs = ["Dockerfile"],
)

sh_library(
    name = "run-services",
    visibility = ["//visibility:public"],
    srcs = ["run_services.sh"],
)

