http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "expat",
    build_file = "@//build_external/expat:BUILD.expat.bazel",
    strip_prefix = "expat-2.6.4",
    urls = ["https://github.com/libexpat/libexpat/releases/download/R_2_6_4/expat-2.6.4.tar.bz2"],
)
