cc_library(
    name = "constants",
    visibility = [ "//visibility:public" ],
    srcs = [
        "gce_metadata_attributes.cpp",
        "gce_metadata_attributes.h",
        "gce_resource_location.cpp",
        "gce_resource_location.h",
    ],
    hdrs = [
        "gce_metadata_attributes.h",
        "gce_resource_location.h",
    ],
)
