host/deploy/install_zip.sh /usr/bin/
host/deploy/unpack_boot_image.py /usr/lib/cuttlefish-common/bin/
host/deploy/capability_query.py /usr/lib/cuttlefish-common/bin/
host/packages/cuttlefish-base/* /
cvd/bazel-bin/cuttlefish/host/commands/assemble_cvd/assemble_cvd /usr/lib/cuttlefish-common/bin/
cvd/bazel-bin/cuttlefish/host/commands/cvd/cvd /usr/lib/cuttlefish-common/bin/
cvd/bazel-bin/cuttlefish/host/commands/logcat_receiver/logcat_receiver /usr/lib/cuttlefish-common/bin/logcat_receiver
