cc_library(
    name = "cuttlefish_logging",
    hdrs = [
        "logging.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@glog_repo//:glog",
        "//common/libs/auto_resources",
    ],
)
