#!/bin/bash

set -e
set -x

cd $1
shift

# Override these variables to make go not depend on HOME
mkdir -p /tmp/go
export GOPATH=/tmp/go
export GOCACHE=/tmp/go/go-build

GOBIN=go
if ! command -v go &> /dev/null
then
  GOBIN=/usr/lib/go-1.13/bin/go
fi

$GOBIN "$@"
