load("//cuttlefish/bazel:rules.bzl", "cf_build_test", "cf_cc_binary")

package(
    default_visibility = ["//:android_cuttlefish"],
)

cf_build_test(name = "record_cvd_build_test")

cf_cc_binary(
    name = "record_cvd",
    srcs = ["record_cvd.cc"],
    deps = [
        "//cuttlefish/common/libs/utils:tee_logging",
        "//cuttlefish/host/libs/config:config_utils",
        "//cuttlefish/host/libs/config:cuttlefish_config",
        "//cuttlefish/host/libs/screen_recording_controls",
        "//cuttlefish/result",
        "@abseil-cpp//absl/log",
        "@gflags",
    ],
)
