# Auto-Generated by cargo-bitbake 0.3.16
#
inherit cargo

# If this is git based prefer versioned ones if they exist
# DEFAULT_PREFERENCE = "-1"

# how to get crosvm could be as easy as but default to a git checkout:
# SRC_URI += "crate://crates.io/crosvm/0.1.0"
SRC_URI += "gitsm://chromium.googlesource.com/crosvm/crosvm;protocol=https;nobranch=1"
SRCREV = "d57dd410776287b2e87be364acf2947bc3b34a48"
S = "${WORKDIR}/git"
CARGO_SRC_DIR = ""
PV:append = ".AUTOINC+d57dd41077"

# please note if you have entries that do not begin with crate://
# you must change them to how that package can be fetched
SRC_URI += " \
    crate://crates.io/addr2line/0.21.0 \
    crate://crates.io/adler/1.0.2 \
    crate://crates.io/ahash/0.8.6 \
    crate://crates.io/aho-corasick/0.7.18 \
    crate://crates.io/android_log-sys/0.3.1 \
    crate://crates.io/anyhow/1.0.58 \
    crate://crates.io/arbitrary/1.1.6 \
    crate://crates.io/argh/0.1.10 \
    crate://crates.io/argh_derive/0.1.10 \
    crate://crates.io/argh_shared/0.1.10 \
    crate://crates.io/ash/0.37.3+1.3.251 \
    crate://crates.io/async-task/4.3.0 \
    crate://crates.io/async-trait/0.1.85 \
    crate://crates.io/atty/0.2.14 \
    crate://crates.io/autocfg/1.1.0 \
    crate://crates.io/backtrace/0.3.69 \
    crate://crates.io/bindgen/0.63.0 \
    crate://crates.io/bindgen/0.68.1 \
    crate://crates.io/bindgen/0.70.1 \
    crate://crates.io/bitflags/1.3.2 \
    crate://crates.io/bitflags/2.4.0 \
    crate://crates.io/bitreader/0.3.6 \
    crate://crates.io/bytemuck/1.14.0 \
    crate://crates.io/bytemuck_derive/1.5.0 \
    crate://crates.io/byteorder/1.4.3 \
    crate://crates.io/bytes/1.2.0 \
    crate://crates.io/cbindgen/0.24.3 \
    crate://crates.io/cc/1.0.90 \
    crate://crates.io/cexpr/0.6.0 \
    crate://crates.io/cfg-if/1.0.0 \
    crate://crates.io/cfg_aliases/0.1.1 \
    crate://crates.io/cfg_aliases/0.2.1 \
    crate://crates.io/chrono/0.4.35 \
    crate://crates.io/ciborium-io/0.2.2 \
    crate://crates.io/ciborium-ll/0.2.2 \
    crate://crates.io/ciborium/0.2.2 \
    crate://crates.io/clang-sys/1.4.0 \
    crate://crates.io/clap/3.2.23 \
    crate://crates.io/clap/4.1.8 \
    crate://crates.io/clap_derive/4.1.8 \
    crate://crates.io/clap_lex/0.2.4 \
    crate://crates.io/clap_lex/0.3.2 \
    crate://crates.io/core-foundation-sys/0.8.6 \
    crate://crates.io/core-foundation/0.9.4 \
    crate://crates.io/core-graphics-types/0.1.3 \
    crate://crates.io/crc32fast/1.3.2 \
    crate://crates.io/cros-codecs/0.0.4 \
    crate://crates.io/cros-libva/0.0.4 \
    crate://crates.io/crossbeam-channel/0.5.8 \
    crate://crates.io/crossbeam-deque/0.8.3 \
    crate://crates.io/crossbeam-epoch/0.9.14 \
    crate://crates.io/crossbeam-queue/0.3.11 \
    crate://crates.io/crossbeam-utils/0.8.19 \
    crate://crates.io/crunchy/0.2.2 \
    crate://crates.io/ctrlc/3.2.5 \
    crate://crates.io/dbus/0.9.7 \
    crate://crates.io/derive-into-owned/0.1.0 \
    crate://crates.io/difference/1.0.0 \
    crate://crates.io/document-features/0.2.6 \
    crate://crates.io/downcast-rs/1.2.1 \
    crate://crates.io/either/1.7.0 \
    crate://crates.io/enumn/0.1.13 \
    crate://crates.io/env_logger/0.9.0 \
    crate://crates.io/equivalent/1.0.1 \
    crate://crates.io/errno-dragonfly/0.1.2 \
    crate://crates.io/errno/0.2.8 \
    crate://crates.io/euclid/0.22.7 \
    crate://crates.io/fastrand/1.8.0 \
    crate://crates.io/fnv/1.0.7 \
    crate://crates.io/foreign-types-shared/0.1.1 \
    crate://crates.io/foreign-types/0.3.2 \
    crate://crates.io/form_urlencoded/1.1.0 \
    crate://crates.io/futures-channel/0.3.21 \
    crate://crates.io/futures-core/0.3.21 \
    crate://crates.io/futures-executor/0.3.21 \
    crate://crates.io/futures-io/0.3.21 \
    crate://crates.io/futures-macro/0.3.21 \
    crate://crates.io/futures-sink/0.3.21 \
    crate://crates.io/futures-task/0.3.21 \
    crate://crates.io/futures-util/0.3.21 \
    crate://crates.io/futures/0.3.21 \
    crate://crates.io/gdbstub/0.7.0 \
    crate://crates.io/gdbstub_arch/0.3.0 \
    crate://crates.io/getrandom/0.2.7 \
    crate://crates.io/gimli/0.28.1 \
    crate://crates.io/glob/0.3.0 \
    crate://crates.io/half/2.4.1 \
    crate://crates.io/hashbrown/0.12.3 \
    crate://crates.io/hashbrown/0.15.0 \
    crate://crates.io/heck/0.4.0 \
    crate://crates.io/hermit-abi/0.1.19 \
    crate://crates.io/hermit-abi/0.3.1 \
    crate://crates.io/idna/0.3.0 \
    crate://crates.io/indexmap/1.9.1 \
    crate://crates.io/indexmap/2.6.0 \
    crate://crates.io/instant/0.1.12 \
    crate://crates.io/intrusive-collections/0.9.6 \
    crate://crates.io/io-lifetimes/1.0.5 \
    crate://crates.io/is-terminal/0.4.4 \
    crate://crates.io/itertools/0.12.1 \
    crate://crates.io/itoa/1.0.2 \
    crate://crates.io/jobserver/0.1.24 \
    crate://crates.io/lazy_static/1.4.0 \
    crate://crates.io/lazycell/1.3.0 \
    crate://crates.io/libc/0.2.161 \
    crate://crates.io/libdbus-sys/0.2.5 \
    crate://crates.io/libfuzzer-sys/0.4.4 \
    crate://crates.io/libloading/0.7.3 \
    crate://crates.io/libslirp-sys/4.2.1 \
    crate://crates.io/libtest-mimic/0.6.0 \
    crate://crates.io/linux-raw-sys/0.1.4 \
    crate://crates.io/litrs/0.2.3 \
    crate://crates.io/lock_api/0.4.9 \
    crate://crates.io/log/0.4.21 \
    crate://crates.io/lz4_flex/0.11.1 \
    crate://crates.io/malloc_buf/0.0.6 \
    crate://crates.io/managed/0.8.0 \
    crate://crates.io/memchr/2.5.0 \
    crate://crates.io/memoffset/0.8.0 \
    crate://crates.io/memoffset/0.9.0 \
    crate://crates.io/merge/0.1.0 \
    crate://crates.io/merge_derive/0.1.0 \
    crate://crates.io/minimal-lexical/0.2.1 \
    crate://crates.io/miniz_oxide/0.7.2 \
    crate://crates.io/named-lock/0.3.0 \
    crate://crates.io/nix/0.26.2 \
    crate://crates.io/nix/0.27.1 \
    crate://crates.io/nix/0.28.0 \
    crate://crates.io/nix/0.29.0 \
    crate://crates.io/nom/7.1.1 \
    crate://crates.io/num-traits/0.2.15 \
    crate://crates.io/num_cpus/1.13.1 \
    crate://crates.io/objc/0.2.7 \
    crate://crates.io/object/0.32.2 \
    crate://crates.io/once_cell/1.17.0 \
    crate://crates.io/openssl-macros/0.1.0 \
    crate://crates.io/openssl-sys/0.9.86 \
    crate://crates.io/openssl/0.10.51 \
    crate://crates.io/os_str_bytes/6.4.1 \
    crate://crates.io/p9/0.3.2 \
    crate://crates.io/p9_wire_format_derive/0.3.0 \
    crate://crates.io/parking_lot/0.12.1 \
    crate://crates.io/parking_lot_core/0.9.6 \
    crate://crates.io/paste/1.0.7 \
    crate://crates.io/pcap-file/1.1.1 \
    crate://crates.io/peeking_take_while/0.1.2 \
    crate://crates.io/percent-encoding/2.2.0 \
    crate://crates.io/pin-project-lite/0.2.13 \
    crate://crates.io/pin-utils/0.1.0 \
    crate://crates.io/pkg-config/0.3.31 \
    crate://crates.io/ppv-lite86/0.2.16 \
    crate://crates.io/pretty_assertions/0.2.1 \
    crate://crates.io/prettyplease/0.2.22 \
    crate://crates.io/proc-macro-crate/1.3.1 \
    crate://crates.io/proc-macro-error-attr/1.0.4 \
    crate://crates.io/proc-macro-error/1.0.4 \
    crate://crates.io/proc-macro2/0.4.30 \
    crate://crates.io/proc-macro2/1.0.85 \
    crate://crates.io/protobuf-codegen/3.7.2 \
    crate://crates.io/protobuf-parse/3.7.2 \
    crate://crates.io/protobuf-support/3.7.2 \
    crate://crates.io/protobuf/3.7.2 \
    crate://crates.io/quote/0.3.15 \
    crate://crates.io/quote/0.6.13 \
    crate://crates.io/quote/1.0.36 \
    crate://crates.io/rand/0.8.5 \
    crate://crates.io/rand_chacha/0.3.1 \
    crate://crates.io/rand_core/0.6.3 \
    crate://crates.io/rayon-core/1.11.0 \
    crate://crates.io/rayon/1.7.0 \
    crate://crates.io/redox_syscall/0.2.15 \
    crate://crates.io/regex-syntax/0.6.27 \
    crate://crates.io/regex/1.6.0 \
    crate://crates.io/remain/0.2.6 \
    crate://crates.io/remove_dir_all/0.5.3 \
    crate://crates.io/rustc-demangle/0.1.23 \
    crate://crates.io/rustc-hash/1.1.0 \
    crate://crates.io/rustix/0.36.8 \
    crate://crates.io/ryu/1.0.10 \
    crate://crates.io/same-file/1.0.6 \
    crate://crates.io/scopeguard/1.1.0 \
    crate://crates.io/scudo-proc-macros/0.1.0 \
    crate://crates.io/scudo-sys/0.2.2 \
    crate://crates.io/scudo/0.1.3 \
    crate://crates.io/serde/1.0.140 \
    crate://crates.io/serde_derive/1.0.140 \
    crate://crates.io/serde_json/1.0.82 \
    crate://crates.io/shlex/1.3.0 \
    crate://crates.io/slab/0.4.7 \
    crate://crates.io/smallvec/1.9.0 \
    crate://crates.io/snapshot-proc-macro/0.1.0 \
    crate://crates.io/snapshot/0.1.0 \
    crate://crates.io/static_assertions/1.1.0 \
    crate://crates.io/strsim/0.10.0 \
    crate://crates.io/syn/0.11.11 \
    crate://crates.io/syn/0.14.9 \
    crate://crates.io/syn/1.0.103 \
    crate://crates.io/syn/2.0.77 \
    crate://crates.io/synom/0.11.3 \
    crate://crates.io/tempfile/3.3.0 \
    crate://crates.io/termcolor/1.1.3 \
    crate://crates.io/textwrap/0.16.0 \
    crate://crates.io/thiserror-impl/1.0.38 \
    crate://crates.io/thiserror/1.0.38 \
    crate://crates.io/thread_local/1.1.8 \
    crate://crates.io/threadpool/1.8.1 \
    crate://crates.io/tinyvec/1.6.0 \
    crate://crates.io/tinyvec_macros/0.1.0 \
    crate://crates.io/tokio/1.29.1 \
    crate://crates.io/toml/0.5.9 \
    crate://crates.io/toml_datetime/0.6.8 \
    crate://crates.io/toml_edit/0.19.15 \
    crate://crates.io/twox-hash/1.6.3 \
    crate://crates.io/unicode-bidi/0.3.8 \
    crate://crates.io/unicode-ident/1.0.2 \
    crate://crates.io/unicode-normalization/0.1.22 \
    crate://crates.io/unicode-xid/0.0.4 \
    crate://crates.io/unicode-xid/0.1.0 \
    crate://crates.io/url/2.3.1 \
    crate://crates.io/userfaultfd-sys/0.5.0 \
    crate://crates.io/userfaultfd/0.8.1 \
    crate://crates.io/uuid/1.8.0 \
    crate://crates.io/v4l2r/0.0.6 \
    crate://crates.io/vcpkg/0.2.15 \
    crate://crates.io/version_check/0.9.4 \
    crate://crates.io/virtio-media/0.0.7 \
    crate://crates.io/vk-parse/0.8.0 \
    crate://crates.io/vulkano-macros/0.33.0 \
    crate://crates.io/vulkano/0.31.1 \
    crate://crates.io/vulkano/0.33.0 \
    crate://crates.io/walkdir/2.5.0 \
    crate://crates.io/wasi/0.11.0+wasi-snapshot-preview1 \
    crate://crates.io/which/4.2.5 \
    crate://crates.io/widestring/1.0.2 \
    crate://crates.io/winapi-i686-pc-windows-gnu/0.4.0 \
    crate://crates.io/winapi-util/0.1.5 \
    crate://crates.io/winapi-x86_64-pc-windows-gnu/0.4.0 \
    crate://crates.io/winapi/0.3.9 \
    crate://crates.io/windows-sys/0.42.0 \
    crate://crates.io/windows-sys/0.45.0 \
    crate://crates.io/windows-targets/0.42.1 \
    crate://crates.io/windows/0.39.0 \
    crate://crates.io/windows_aarch64_gnullvm/0.42.1 \
    crate://crates.io/windows_aarch64_msvc/0.39.0 \
    crate://crates.io/windows_aarch64_msvc/0.42.1 \
    crate://crates.io/windows_i686_gnu/0.39.0 \
    crate://crates.io/windows_i686_gnu/0.42.1 \
    crate://crates.io/windows_i686_msvc/0.39.0 \
    crate://crates.io/windows_i686_msvc/0.42.1 \
    crate://crates.io/windows_x86_64_gnu/0.39.0 \
    crate://crates.io/windows_x86_64_gnu/0.42.1 \
    crate://crates.io/windows_x86_64_gnullvm/0.42.1 \
    crate://crates.io/windows_x86_64_msvc/0.39.0 \
    crate://crates.io/windows_x86_64_msvc/0.42.1 \
    crate://crates.io/winnow/0.5.40 \
    crate://crates.io/wio/0.2.2 \
    crate://crates.io/xml-rs/0.8.19 \
    crate://crates.io/zerocopy-derive/0.7.32 \
    crate://crates.io/zerocopy-derive/0.8.14 \
    crate://crates.io/zerocopy/0.7.32 \
    crate://crates.io/zerocopy/0.8.14 \
    crate://crates.io/zeroize/1.5.7 \
    crate://crates.io/zstd-safe/7.2.1 \
    crate://crates.io/zstd-sys/2.0.13+zstd.1.5.6 \
    crate://crates.io/zstd/0.13.2 \
"



# FIXME: update generateme with the real MD5 of the license file
LIC_FILES_CHKSUM = " \
    "

SUMMARY = "crosvm"
HOMEPAGE = "https://github.com/google/crosvm.git"
LICENSE = "CLOSED"

# includes this file if it exists but does not fail
# this is useful for anything you may want to override from
# what cargo-bitbake generates.
include crosvm-${PV}.inc
include crosvm.inc
