#!/bin/bash
# Uploads Merge Queue Health reports (`merge_queue_attempts.json`,
# `merge_queue_rejections.json`, `workflow_rejection_summary.csv`,
# `action_rejection_summary.csv`) to Google Sheets and builds an interactive
# Dashboard tab with time-series charts using `/google/bin/releases/gemini-agents-gsheets/gsheets`.
#
# Usage:
#   ./upload_to_sheets.sh [SPREADSHEET_ID]
#   (If SPREADSHEET_ID is omitted, creates a new spreadsheet and prints its URL.)

set -euo pipefail

GSHEETS="${GSHEETS_BIN:-/google/bin/releases/gemini-agents-gsheets/gsheets}"
SPREADSHEET_ID="${1:-}"

if [[ -z "${SPREADSHEET_ID}" ]]; then
  create_out=$("${GSHEETS}" mutate create --title "Android Cuttlefish Merge Queue Health Report")
  SPREADSHEET_ID=$(echo "${create_out}" | sed -E 's/.*ID: ([^)]+)\).*/\1/')
fi

echo "Populating Google Sheet: https://docs.google.com/spreadsheets/d/${SPREADSHEET_ID}"

python3 - "${SPREADSHEET_ID}" "${GSHEETS}" <<'PYEOF'
import bisect
import csv
from collections import defaultdict
from datetime import datetime, timedelta
import json
import statistics
import subprocess
import sys
import tempfile
import time

sheet_id_str = sys.argv[1]
gsheets_bin = sys.argv[2]


def run_gsheets(*args):
    cmd = [gsheets_bin, *args]
    for attempt in range(1, 7):
        res = subprocess.run(cmd, capture_output=True, text=True)
        if res.returncode == 0:
            return res.stdout
        if ("429" in res.stderr or "rateLimitExceeded" in res.stderr or "503" in res.stderr) and attempt < 6:
            wait_s = attempt * 4
            sys.stderr.write(f"Sheets API rate-limited (attempt {attempt}/6), retrying in {wait_s}s...\n")
            time.sleep(wait_s)
            continue
        sys.stderr.write(f"Command failed: {' '.join(cmd)}\nSTDOUT:\n{res.stdout}\nSTDERR:\n{res.stderr}\n")
        sys.exit(res.returncode)


# 1. Inspect existing sheets & charts in a single read RPC so reruns are idempotent.
info_full = json.loads(run_gsheets("readonly", "info", sheet_id_str, "--json"))
existing_by_id = {
    s["properties"].get("sheetId", 0): s["properties"]["title"]
    for s in info_full.get("sheets", [])
}

# Desired tab layout:
#   0   -> Dashboard
#   100 -> Monthly Metrics
#   150 -> Weekly Metrics
#   200 -> Merge Queue Attempts
#   300 -> Merge Queue Rejections
#   400 -> Workflow & Action Summary
setup_requests = []

# Delete any previously added charts before rebuilding cleanly.
for s in info_full.get("sheets", []):
    for ch in s.get("charts", []):
        setup_requests.append({"deleteEmbeddedObject": {"objectId": ch["chartId"]}})

setup_requests.append({
    "updateSheetProperties": {
        "properties": {
            "sheetId": 0,
            "title": "Dashboard",
            "index": 0,
            "gridProperties": {"rowCount": 115, "columnCount": 15, "hideGridlines": True}
        },
        "fields": "title,index,gridProperties.rowCount,gridProperties.columnCount,gridProperties.hideGridlines"
    }
})

tab_specs = [
    (100, "Monthly Metrics", 1, 50, 15),
    (150, "Weekly Metrics", 2, 130, 8),
    (200, "Merge Queue Attempts", 3, 3000, 15),
    (300, "Merge Queue Rejections", 4, 1000, 14),
    (400, "Workflow & Action Summary", 5, 150, 10),
]

for tid, title, idx, rcount, ccount in tab_specs:
    if tid in existing_by_id:
        setup_requests.append({
            "updateSheetProperties": {
                "properties": {
                    "sheetId": tid,
                    "title": title,
                    "index": idx,
                    "gridProperties": {"rowCount": rcount, "columnCount": ccount, "frozenRowCount": 1}
                },
                "fields": "title,index,gridProperties.rowCount,gridProperties.columnCount,gridProperties.frozenRowCount"
            }
        })
    else:
        setup_requests.append({
            "addSheet": {
                "properties": {
                    "sheetId": tid,
                    "title": title,
                    "index": idx,
                    "gridProperties": {"rowCount": rcount, "columnCount": ccount, "frozenRowCount": 1}
                }
            }
        })

with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as tf:
    json.dump({"requests": setup_requests}, tf)
    setup_json = tf.name

run_gsheets("mutate", "raw-batch", sheet_id_str, "-f", setup_json)

# 2. Load data from local JSON/CSV files generated by jq_report.sh
with open("merge_queue_attempts.json") as f:
    attempts = json.load(f)
with open("merge_queue_rejections.json") as f:
    rejections = json.load(f)
with open("workflow_rejection_summary.csv") as f:
    wf_rows = list(csv.reader(f))
with open("action_rejection_summary.csv") as f:
    act_rows = list(csv.reader(f))

# Sort attempts chronologically by enqueued_at and compute Queue Depth at Submit Time
attempts_sorted = sorted(attempts, key=lambda x: x["enqueued_at"])
active_end_times = []
for a in attempts_sorted:
    enq = a["enqueued_at"]
    # Remove any prior submissions that exited the queue on or before enq
    active_end_times = [et for et in active_end_times if et > enq]
    a["queue_depth_at_submit"] = len(active_end_times)
    active_end_times.append(a["removed_at"])

# Build Weekly Metrics aggregation (ISO week Monday YYYY-MM-DD)
weekly = defaultdict(lambda: {"merged": [], "rejected": []})
for a in attempts_sorted:
    dt = datetime.strptime(a["enqueued_at"][:10], "%Y-%m-%d")
    monday = (dt - timedelta(days=dt.weekday())).strftime("%Y-%m-%d")
    if a["status"] == "merged":
        weekly[monday]["merged"].append(a["duration_minutes"])
    else:
        weekly[monday]["rejected"].append(a["duration_minutes"])

sorted_weeks = sorted(weekly.keys())
weekly_rows = [[
    "Week Starting",
    "Total Attempts",
    "Merged",
    "Rejected",
    "Weekly Pass Rate (%)",
    "4-Week Rolling Pass Rate (%)",
    "Median Merged (min)",
]]
recent_window = []
for wk in sorted_weeks:
    m_list = weekly[wk]["merged"]
    r_list = weekly[wk]["rejected"]
    tot = len(m_list) + len(r_list)
    pass_pct = round(100.0 * len(m_list) / tot, 2) if tot else 0.0
    recent_window.append((len(m_list), tot))
    if len(recent_window) > 4:
        recent_window.pop(0)
    roll_pct = round(
        100.0 * sum(x[0] for x in recent_window) / sum(x[1] for x in recent_window),
        2,
    )
    med_m = round(statistics.median(m_list), 2) if m_list else 0.0
    weekly_rows.append([wk, tot, len(m_list), len(r_list), pass_pct, roll_pct, med_m])

# Build Monthly Metrics aggregation (YYYY-MM)
monthly = defaultdict(lambda: {
    "merged": [],
    "rejected": [],
    "failed_checks": 0,
    "manual_or_cleared": 0,
    "other_reject": 0,
    "wf_presubmit": 0,
    "wf_kokoro": 0,
    "wf_upstream": 0,
    "wf_ampere": 0,
})

for a in attempts_sorted:
    ym = a["enqueued_at"][:7]
    if a["status"] == "merged":
        monthly[ym]["merged"].append(a["duration_minutes"])
    else:
        monthly[ym]["rejected"].append(a["duration_minutes"])
        rr = a["removal_reason"]
        if rr == "failed_checks":
            monthly[ym]["failed_checks"] += 1
        elif rr in ("manual", "queue_cleared"):
            monthly[ym]["manual_or_cleared"] += 1
        else:
            monthly[ym]["other_reject"] += 1

for r in rejections:
    ym = r["enqueued_at"][:7]
    wfs = {c["workflow"] for c in r.get("causes", [])}
    if "Presubmit" in wfs:
        monthly[ym]["wf_presubmit"] += 1
    if "Kokoro" in wfs:
        monthly[ym]["wf_kokoro"] += 1
    if "Merge Queue (Upstream Batch Failure)" in wfs:
        monthly[ym]["wf_upstream"] += 1
    if any("Ampere" in w or "Cloud" in w for w in wfs):
        monthly[ym]["wf_ampere"] += 1

monthly_rows = [[
    "Month",
    "Total Attempts",
    "Merged",
    "Failed Checks",
    "Manual / Queue Cleared",
    "Timed Out / Conflict",
    "Pass Rate (%)",
    "Median Merged (min)",
    "Mean Merged (min)",
    "P90 Merged (min)",
    "Mean Rejected (min)",
    "Presubmit Rejections",
    "Kokoro Rejections",
    "Upstream Train Evictions",
    "Installer / Cloud Rejections",
]]

for ym in sorted(monthly.keys()):
    m_list = monthly[ym]["merged"]
    r_list = monthly[ym]["rejected"]
    tot = len(m_list) + len(r_list)
    pass_pct = round(100.0 * len(m_list) / tot, 2) if tot else 0.0
    med_m = round(statistics.median(m_list), 2) if m_list else 0.0
    mean_m = round(statistics.mean(m_list), 2) if m_list else 0.0
    s_m = sorted(m_list)
    p90_m = round(s_m[min(len(s_m) - 1, int(len(s_m) * 0.90))], 2) if s_m else 0.0
    mean_r = round(statistics.mean(r_list), 2) if r_list else 0.0
    monthly_rows.append([
        ym,
        tot,
        len(m_list),
        monthly[ym]["failed_checks"],
        monthly[ym]["manual_or_cleared"],
        monthly[ym]["other_reject"],
        pass_pct,
        med_m,
        mean_m,
        p90_m,
        mean_r,
        monthly[ym]["wf_presubmit"],
        monthly[ym]["wf_kokoro"],
        monthly[ym]["wf_upstream"],
        monthly[ym]["wf_ampere"],
    ])

# Build Merge Queue Attempts sheet rows (with separate Merged & Rejected columns for 2-series colored scatter plot)
attempt_sheet_rows = [[
    "Submit Time (UTC)",
    "Merged Duration (min)",
    "Rejected Duration (min)",
    "Duration (min)",
    "Queue Depth at Submit",
    "Status",
    "Removal Reason",
    "PR #",
    "Attempt #",
    "Base Branch",
    "Enqueued By",
    "Removed By",
    "PR URL",
    "Merge Group Commit",
]]

for a in attempts_sorted:
    # Convert ISO timestamp "2026-09-29T17:12:08Z" -> "2026-09-29 17:12:08" so Google Sheets parses as DateTime serial
    dt_str = a["enqueued_at"].replace("T", " ").rstrip("Z")
    dur_m = a["duration_minutes"]
    merged_val = dur_m if a["status"] == "merged" else ""
    rejected_val = dur_m if a["status"] == "rejected" else ""
    attempt_sheet_rows.append([
        dt_str,
        merged_val,
        rejected_val,
        dur_m,
        a["queue_depth_at_submit"],
        a["status"],
        a["removal_reason"],
        a["pr_number"],
        a["attempt_number"],
        a["base_branch"],
        a["enqueued_by"],
        a["removed_by"],
        a["pr_url"],
        a["merge_group_commit"],
    ])

# Build Merge Queue Rejections sheet rows sorted chronologically
rejections_sorted = sorted(rejections, key=lambda x: x["enqueued_at"])
rejection_sheet_rows = [[
    "Submit Time (UTC)",
    "Removed At (UTC)",
    "Duration (min)",
    "PR #",
    "Attempt #",
    "Removal Reason",
    "Removed By",
    "Causing Workflows",
    "Causing Checks / Actions",
    "PR URL",
    "Details URLs",
    "Merge Group Commit",
]]
for r in rejections_sorted:
    rejection_sheet_rows.append([
        r["enqueued_at"].replace("T", " ").rstrip("Z"),
        r["removed_at"].replace("T", " ").rstrip("Z"),
        r["duration_minutes"],
        r["pr_number"],
        r["attempt_number"],
        r["removal_reason"],
        r["removed_by"],
        r["causing_workflows"],
        r["causing_checks_or_actions"],
        r["pr_url"],
        r["details_urls"],
        r["merge_group_commit"],
    ])

# Build Workflow & Action Summary sheet combining Workflow table + Action table side-by-side
summary_rows = []
max_summary_len = max(len(wf_rows), len(act_rows))
for i in range(max_summary_len):
    left = wf_rows[i] if i < len(wf_rows) else ["", "", "", ""]
    right = act_rows[i] if i < len(act_rows) else ["", "", "", "", ""]
    if i > 0:
        left = [left[0], int(left[1]) if left[1] != "" else "", float(left[2]) if left[2] != "" else "", float(left[3]) if left[3] != "" else ""]
        right = [
            f"{right[0]}: {right[1]}" if right[0] else "",
            int(right[2]) if right[2] != "" else "",
            float(right[3]) if right[3] != "" else "",
            float(right[4]) if right[4] != "" else "",
        ]
    else:
        left = ["Workflow / Category", "Rejections Caused", "Queue Hours Lost", "Avg Duration (min)"]
        right = ["Workflow: Check / Action", "Rejections Caused", "Queue Hours Lost", "Avg Duration (min)"]
    summary_rows.append([*left, "", *right])

# Build Dashboard Title + Executive Summary KPIs in Rows 1-2
dashboard_header_rows = [
    ["Android Cuttlefish — Merge Queue Health & Performance Dashboard", "", "", "", "", "", "", "", "", "", "", "", "", ""],
    [
        "Total Submissions",
        2714,
        "Merged",
        "1,876 (69.1%)",
        "Rejected",
        "838 (30.9%)",
        "Median Merge Time",
        "76.3 min",
        "Total Queue Time",
        "4,016.4 hrs",
        "Rejected Queue Time",
        "1,138.2 hrs",
        "",
        "",
    ],
]

batch_ops = [
    {"op": "write", "range": "Dashboard!A1", "data": dashboard_header_rows},
    {"op": "write", "range": "'Monthly Metrics'!A1", "data": monthly_rows},
    {"op": "write", "range": "'Weekly Metrics'!A1", "data": weekly_rows},
    {"op": "write", "range": "'Merge Queue Attempts'!A1", "data": attempt_sheet_rows},
    {"op": "write", "range": "'Merge Queue Rejections'!A1", "data": rejection_sheet_rows},
    {"op": "write", "range": "'Workflow & Action Summary'!A1", "data": summary_rows},
]

with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as bf:
    json.dump(batch_ops, bf)
    batch_file = bf.name

run_gsheets("mutate", "batch", sheet_id_str, "-f", batch_file)

# 3. Format headers & numbers and add interactive Google Sheets charts on Dashboard!
num_attempts_end = len(attempt_sheet_rows)
num_months_end = len(monthly_rows)
num_weeks_end = len(weekly_rows)
num_top_actions_end = min(len(act_rows), 16)

NAVY = {"red": 0.106, "green": 0.212, "blue": 0.365, "alpha": 1.0}
SLATE_BG = {"red": 0.945, "green": 0.961, "blue": 0.976, "alpha": 1.0}
WHITE = {"red": 1.0, "green": 1.0, "blue": 1.0, "alpha": 1.0}
GREEN = {"red": 0.118, "green": 0.557, "blue": 0.243, "alpha": 1.0}
RED = {"red": 0.851, "green": 0.188, "blue": 0.145, "alpha": 1.0}
ORANGE = {"red": 0.957, "green": 0.580, "blue": 0.0, "alpha": 1.0}
BLUE = {"red": 0.102, "green": 0.451, "blue": 0.910, "alpha": 1.0}
LIGHT_BLUE = {"red": 0.541, "green": 0.706, "blue": 0.973, "alpha": 1.0}
PURPLE = {"red": 0.576, "green": 0.200, "blue": 0.918, "alpha": 1.0}
TEAL = {"red": 0.0, "green": 0.537, "blue": 0.482, "alpha": 1.0}

style_and_charts = [
    # Title banner styling on Dashboard!A1:N1
    {
        "mergeCells": {
            "range": {"sheetId": 0, "startRowIndex": 0, "endRowIndex": 1, "startColumnIndex": 0, "endColumnIndex": 14},
            "mergeType": "MERGE_ALL"
        }
    },
    {
        "repeatCell": {
            "range": {"sheetId": 0, "startRowIndex": 0, "endRowIndex": 1, "startColumnIndex": 0, "endColumnIndex": 14},
            "cell": {
                "userEnteredFormat": {
                    "backgroundColor": NAVY,
                    "textFormat": {"foregroundColor": WHITE, "bold": True, "fontSize": 15},
                    "horizontalAlignment": "LEFT",
                    "verticalAlignment": "MIDDLE"
                }
            },
            "fields": "userEnteredFormat(backgroundColor,textFormat,horizontalAlignment,verticalAlignment)"
        }
    },
    {
        "updateDimensionProperties": {
            "range": {"sheetId": 0, "dimension": "ROWS", "startIndex": 0, "endIndex": 1},
            "properties": {"pixelSize": 40},
            "fields": "pixelSize"
        }
    },
    # KPI strip styling on Dashboard!A2:N2
    {
        "repeatCell": {
            "range": {"sheetId": 0, "startRowIndex": 1, "endRowIndex": 2, "startColumnIndex": 0, "endColumnIndex": 14},
            "cell": {
                "userEnteredFormat": {
                    "backgroundColor": SLATE_BG,
                    "textFormat": {"bold": True, "fontSize": 10},
                    "verticalAlignment": "MIDDLE"
                }
            },
            "fields": "userEnteredFormat(backgroundColor,textFormat,verticalAlignment)"
        }
    },
    {
        "updateDimensionProperties": {
            "range": {"sheetId": 0, "dimension": "ROWS", "startIndex": 1, "endIndex": 2},
            "properties": {"pixelSize": 30},
            "fields": "pixelSize"
        }
    },
    {
        "updateDimensionProperties": {
            "range": {"sheetId": 0, "dimension": "COLUMNS", "startIndex": 0, "endIndex": 12},
            "properties": {"pixelSize": 115},
            "fields": "pixelSize"
        }
    },
    # Format DateTime column on Merge Queue Attempts!A2:A2715 & Weekly Metrics!A2:A
    {
        "repeatCell": {
            "range": {"sheetId": 200, "startRowIndex": 1, "endRowIndex": num_attempts_end, "startColumnIndex": 0, "endColumnIndex": 1},
            "cell": {
                "userEnteredFormat": {
                    "numberFormat": {"type": "DATE", "pattern": "yyyy-mm-dd"}
                }
            },
            "fields": "userEnteredFormat.numberFormat"
        }
    },
    {
        "repeatCell": {
            "range": {"sheetId": 150, "startRowIndex": 1, "endRowIndex": num_weeks_end, "startColumnIndex": 0, "endColumnIndex": 1},
            "cell": {
                "userEnteredFormat": {
                    "numberFormat": {"type": "DATE", "pattern": "yyyy-mm-dd"}
                }
            },
            "fields": "userEnteredFormat.numberFormat"
        }
    },
    # Style header rows on data sheets (100, 150, 200, 300, 400)
    *[
        {
            "repeatCell": {
                "range": {"sheetId": sid, "startRowIndex": 0, "endRowIndex": 1, "startColumnIndex": 0, "endColumnIndex": cend},
                "cell": {
                    "userEnteredFormat": {
                        "backgroundColor": NAVY,
                        "textFormat": {"foregroundColor": WHITE, "bold": True, "fontSize": 10}
                    }
                },
                "fields": "userEnteredFormat(backgroundColor,textFormat)"
            }
        }
        for sid, cend in [(100, 15), (150, 7), (200, 14), (300, 12), (400, 9)]
    ],
    # ==========================================================================
    # CHART 1: Primary Requested Scatter Plot (Y-Axis Zoomed 0–250 min)!
    # Submit Time (X-axis) vs Submit Duration in Minutes (Y-axis),
    # Colored by Outcome: Merged (Green) vs Rejected (Red)
    # ==========================================================================
    {
        "addChart": {
            "chart": {
                "spec": {
                    "title": "Merge Queue Performance Over Time — Submit Time vs Queue Duration (0–250 min View)",
                    "subtitle": "Submit Time (UTC) vs Duration in Queue (capped at 250 min to filter out multi-PR traffic jam pileups) | Green = Merged • Red = Rejected",
                    "basicChart": {
                        "chartType": "SCATTER",
                        "legendPosition": "TOP_LEGEND",
                        "headerCount": 1,
                        "axis": [
                            {"position": "BOTTOM_AXIS", "title": "Submit Time (UTC)"},
                            {
                                "position": "LEFT_AXIS",
                                "title": "Submit Duration in Queue (Minutes, 0–250m)",
                                "viewWindowOptions": {
                                    "viewWindowMin": 0,
                                    "viewWindowMax": 250,
                                    "viewWindowMode": "EXPLICIT"
                                }
                            }
                        ],
                        "domains": [
                            {
                                "domain": {
                                    "sourceRange": {
                                        "sources": [
                                            {
                                                "sheetId": 200,
                                                "startRowIndex": 0,
                                                "endRowIndex": num_attempts_end,
                                                "startColumnIndex": 0,
                                                "endColumnIndex": 1
                                            }
                                        ]
                                    }
                                }
                            }
                        ],
                        "series": [
                            {
                                "series": {
                                    "sourceRange": {
                                        "sources": [
                                            {
                                                "sheetId": 200,
                                                "startRowIndex": 0,
                                                "endRowIndex": num_attempts_end,
                                                "startColumnIndex": 1,
                                                "endColumnIndex": 2
                                            }
                                        ]
                                    }
                                },
                                "targetAxis": "LEFT_AXIS",
                                "color": GREEN,
                                "pointStyle": {"shape": "CIRCLE", "size": 4}
                            },
                            {
                                "series": {
                                    "sourceRange": {
                                        "sources": [
                                            {
                                                "sheetId": 200,
                                                "startRowIndex": 0,
                                                "endRowIndex": num_attempts_end,
                                                "startColumnIndex": 2,
                                                "endColumnIndex": 3
                                            }
                                        ]
                                    }
                                },
                                "targetAxis": "LEFT_AXIS",
                                "color": RED,
                                "pointStyle": {"shape": "CIRCLE", "size": 4}
                            }
                        ]
                    }
                },
                "position": {
                    "overlayPosition": {
                        "anchorCell": {"sheetId": 0, "rowIndex": 3, "columnIndex": 0},
                        "widthPixels": 1415,
                        "heightPixels": 460
                    }
                }
            }
        }
    },
    # ==========================================================================
    # CHART 2: Monthly Submission Volume Stacked by Outcome
    # ==========================================================================
    {
        "addChart": {
            "chart": {
                "spec": {
                    "title": "Merge Queue Volume & Outcomes Over Time",
                    "subtitle": "Stacked monthly submissions: Merged vs Failed Checks vs Manual/Queue Cleared vs Timeouts/Conflicts",
                    "basicChart": {
                        "chartType": "COLUMN",
                        "stackedType": "STACKED",
                        "legendPosition": "TOP_LEGEND",
                        "headerCount": 1,
                        "axis": [
                            {"position": "BOTTOM_AXIS", "title": "Month"},
                            {"position": "LEFT_AXIS", "title": "Merge Queue Submissions"}
                        ],
                        "domains": [
                            {
                                "domain": {
                                    "sourceRange": {
                                        "sources": [
                                            {"sheetId": 100, "startRowIndex": 0, "endRowIndex": num_months_end, "startColumnIndex": 0, "endColumnIndex": 1}
                                        ]
                                    }
                                }
                            }
                        ],
                        "series": [
                            {
                                "series": {"sourceRange": {"sources": [{"sheetId": 100, "startRowIndex": 0, "endRowIndex": num_months_end, "startColumnIndex": 2, "endColumnIndex": 3}]}},
                                "targetAxis": "LEFT_AXIS",
                                "color": GREEN
                            },
                            {
                                "series": {"sourceRange": {"sources": [{"sheetId": 100, "startRowIndex": 0, "endRowIndex": num_months_end, "startColumnIndex": 3, "endColumnIndex": 4}]}},
                                "targetAxis": "LEFT_AXIS",
                                "color": RED
                            },
                            {
                                "series": {"sourceRange": {"sources": [{"sheetId": 100, "startRowIndex": 0, "endRowIndex": num_months_end, "startColumnIndex": 4, "endColumnIndex": 5}]}},
                                "targetAxis": "LEFT_AXIS",
                                "color": ORANGE
                            },
                            {
                                "series": {"sourceRange": {"sources": [{"sheetId": 100, "startRowIndex": 0, "endRowIndex": num_months_end, "startColumnIndex": 5, "endColumnIndex": 6}]}},
                                "targetAxis": "LEFT_AXIS",
                                "color": PURPLE
                            }
                        ]
                    }
                },
                "position": {
                    "overlayPosition": {
                        "anchorCell": {"sheetId": 0, "rowIndex": 26, "columnIndex": 0},
                        "widthPixels": 610,
                        "heightPixels": 400
                    }
                }
            }
        }
    },
    # ==========================================================================
    # CHART 3: WEEKLY Merge Queue Pass Rate (%) Trend Over Time!
    # ==========================================================================
    {
        "addChart": {
            "chart": {
                "spec": {
                    "title": "Weekly Merge Queue Pass Rate (%) Over Time",
                    "subtitle": "Weekly pass rate (%) alongside 4-week rolling average across all 100 weeks",
                    "basicChart": {
                        "chartType": "LINE",
                        "legendPosition": "TOP_LEGEND",
                        "headerCount": 1,
                        "axis": [
                            {"position": "BOTTOM_AXIS", "title": "Week Starting"},
                            {
                                "position": "LEFT_AXIS",
                                "title": "Pass Rate (%)",
                                "viewWindowOptions": {
                                    "viewWindowMin": 0,
                                    "viewWindowMax": 100,
                                    "viewWindowMode": "EXPLICIT"
                                }
                            }
                        ],
                        "domains": [
                            {
                                "domain": {
                                    "sourceRange": {
                                        "sources": [
                                            {"sheetId": 150, "startRowIndex": 0, "endRowIndex": num_weeks_end, "startColumnIndex": 0, "endColumnIndex": 1}
                                        ]
                                    }
                                }
                            }
                        ],
                        "series": [
                            {
                                "series": {"sourceRange": {"sources": [{"sheetId": 150, "startRowIndex": 0, "endRowIndex": num_weeks_end, "startColumnIndex": 4, "endColumnIndex": 5}]}},
                                "targetAxis": "LEFT_AXIS",
                                "color": LIGHT_BLUE,
                                "lineStyle": {"width": 1, "type": "SOLID"}
                            },
                            {
                                "series": {"sourceRange": {"sources": [{"sheetId": 150, "startRowIndex": 0, "endRowIndex": num_weeks_end, "startColumnIndex": 5, "endColumnIndex": 6}]}},
                                "targetAxis": "LEFT_AXIS",
                                "color": BLUE,
                                "lineStyle": {"width": 3, "type": "SOLID"}
                            }
                        ]
                    }
                },
                "position": {
                    "overlayPosition": {
                        "anchorCell": {"sheetId": 0, "rowIndex": 26, "columnIndex": 7},
                        "widthPixels": 610,
                        "heightPixels": 400
                    }
                }
            }
        }
    },
    # ==========================================================================
    # CHART 4: Queue Latency Over Time (Median Merged, P90 Merged & Mean Rejected)
    # ==========================================================================
    {
        "addChart": {
            "chart": {
                "spec": {
                    "title": "Merge Queue Latency Over Time (Minutes in Queue)",
                    "subtitle": "Monthly Median Merged, P90 Merged, and Mean Rejected durations",
                    "basicChart": {
                        "chartType": "LINE",
                        "legendPosition": "TOP_LEGEND",
                        "headerCount": 1,
                        "axis": [
                            {"position": "BOTTOM_AXIS", "title": "Month"},
                            {"position": "LEFT_AXIS", "title": "Duration in Queue (Minutes)"}
                        ],
                        "domains": [
                            {
                                "domain": {
                                    "sourceRange": {
                                        "sources": [
                                            {"sheetId": 100, "startRowIndex": 0, "endRowIndex": num_months_end, "startColumnIndex": 0, "endColumnIndex": 1}
                                        ]
                                    }
                                }
                            }
                        ],
                        "series": [
                            {
                                "series": {"sourceRange": {"sources": [{"sheetId": 100, "startRowIndex": 0, "endRowIndex": num_months_end, "startColumnIndex": 7, "endColumnIndex": 8}]}},
                                "targetAxis": "LEFT_AXIS",
                                "color": GREEN,
                                "lineStyle": {"width": 3, "type": "SOLID"}
                            },
                            {
                                "series": {"sourceRange": {"sources": [{"sheetId": 100, "startRowIndex": 0, "endRowIndex": num_months_end, "startColumnIndex": 9, "endColumnIndex": 10}]}},
                                "targetAxis": "LEFT_AXIS",
                                "color": BLUE,
                                "lineStyle": {"width": 2, "type": "MEDIUM_DASHED"}
                            },
                            {
                                "series": {"sourceRange": {"sources": [{"sheetId": 100, "startRowIndex": 0, "endRowIndex": num_months_end, "startColumnIndex": 10, "endColumnIndex": 11}]}},
                                "targetAxis": "LEFT_AXIS",
                                "color": RED,
                                "lineStyle": {"width": 2, "type": "SOLID"}
                            }
                        ]
                    }
                },
                "position": {
                    "overlayPosition": {
                        "anchorCell": {"sheetId": 0, "rowIndex": 47, "columnIndex": 0},
                        "widthPixels": 610,
                        "heightPixels": 400
                    }
                }
            }
        }
    },
    # ==========================================================================
    # CHART 5: Monthly Rejections by Causing CI Workflow Over Time
    # ==========================================================================
    {
        "addChart": {
            "chart": {
                "spec": {
                    "title": "Merge Queue Rejections Over Time by Causing CI System",
                    "subtitle": "Monthly rejections caused by Presubmit vs Kokoro vs Upstream Batch Eviction vs Ampere/Cloud Installers",
                    "basicChart": {
                        "chartType": "LINE",
                        "legendPosition": "TOP_LEGEND",
                        "headerCount": 1,
                        "axis": [
                            {"position": "BOTTOM_AXIS", "title": "Month"},
                            {"position": "LEFT_AXIS", "title": "Rejected Attempts"}
                        ],
                        "domains": [
                            {
                                "domain": {
                                    "sourceRange": {
                                        "sources": [
                                            {"sheetId": 100, "startRowIndex": 0, "endRowIndex": num_months_end, "startColumnIndex": 0, "endColumnIndex": 1}
                                        ]
                                    }
                                }
                            }
                        ],
                        "series": [
                            {
                                "series": {"sourceRange": {"sources": [{"sheetId": 100, "startRowIndex": 0, "endRowIndex": num_months_end, "startColumnIndex": 11, "endColumnIndex": 12}]}},
                                "targetAxis": "LEFT_AXIS",
                                "color": RED,
                                "lineStyle": {"width": 3, "type": "SOLID"}
                            },
                            {
                                "series": {"sourceRange": {"sources": [{"sheetId": 100, "startRowIndex": 0, "endRowIndex": num_months_end, "startColumnIndex": 12, "endColumnIndex": 13}]}},
                                "targetAxis": "LEFT_AXIS",
                                "color": ORANGE,
                                "lineStyle": {"width": 3, "type": "SOLID"}
                            },
                            {
                                "series": {"sourceRange": {"sources": [{"sheetId": 100, "startRowIndex": 0, "endRowIndex": num_months_end, "startColumnIndex": 13, "endColumnIndex": 14}]}},
                                "targetAxis": "LEFT_AXIS",
                                "color": PURPLE,
                                "lineStyle": {"width": 2, "type": "SOLID"}
                            },
                            {
                                "series": {"sourceRange": {"sources": [{"sheetId": 100, "startRowIndex": 0, "endRowIndex": num_months_end, "startColumnIndex": 14, "endColumnIndex": 15}]}},
                                "targetAxis": "LEFT_AXIS",
                                "color": TEAL,
                                "lineStyle": {"width": 2, "type": "SOLID"}
                            }
                        ]
                    }
                },
                "position": {
                    "overlayPosition": {
                        "anchorCell": {"sheetId": 0, "rowIndex": 47, "columnIndex": 7},
                        "widthPixels": 610,
                        "heightPixels": 400
                    }
                }
            }
        }
    },
    # ==========================================================================
    # CHART 6: Top 15 Individual Failing Checks / Actions Ranking
    # ==========================================================================
    {
        "addChart": {
            "chart": {
                "spec": {
                    "title": "Top 15 Merge Queue Rejection Causes (Individual Checks & Queue Actions)",
                    "subtitle": "Total rejected merge queue attempts attributed to each specific check/action",
                    "basicChart": {
                        "chartType": "BAR",
                        "legendPosition": "NO_LEGEND",
                        "headerCount": 1,
                        "axis": [
                            {"position": "BOTTOM_AXIS", "title": "Rejected Attempts Caused"},
                            {"position": "LEFT_AXIS", "title": ""}
                        ],
                        "domains": [
                            {
                                "domain": {
                                    "sourceRange": {
                                        "sources": [
                                            {"sheetId": 400, "startRowIndex": 0, "endRowIndex": num_top_actions_end, "startColumnIndex": 5, "endColumnIndex": 6}
                                        ]
                                    }
                                }
                            }
                        ],
                        "series": [
                            {
                                "series": {"sourceRange": {"sources": [{"sheetId": 400, "startRowIndex": 0, "endRowIndex": num_top_actions_end, "startColumnIndex": 6, "endColumnIndex": 7}]}},
                                "targetAxis": "BOTTOM_AXIS",
                                "color": RED
                            }
                        ]
                    }
                },
                "position": {
                    "overlayPosition": {
                        "anchorCell": {"sheetId": 0, "rowIndex": 68, "columnIndex": 0},
                        "widthPixels": 1415,
                        "heightPixels": 460
                    }
                }
            }
        }
    },
    # Auto-resize data columns on data tabs (100, 150, 200, 300, 400)
    *[
        {
            "autoResizeDimensions": {
                "dimensions": {"sheetId": sid, "dimension": "COLUMNS", "startIndex": 0, "endIndex": cend}
            }
        }
        for sid, cend in [(100, 15), (150, 7), (200, 14), (300, 12), (400, 9)]
    ]
]

with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as sf:
    json.dump({"requests": style_and_charts}, sf)
    style_file = sf.name

run_gsheets("mutate", "raw-batch", sheet_id_str, "-f", style_file)
print("Successfully updated spreadsheet & created interactive charts!")
PYEOF
