[patch.crates-io]
# this needs to be at parity with MODULE.bazel
audio_streams = { git = "https://chromium.googlesource.com/crosvm/crosvm", rev = "d3175012b887aee0dc5767aa05cfdab901d65798" }
libcras = { git = "https://chromium.googlesource.com/crosvm/crosvm", rev = "d3175012b887aee0dc5767aa05cfdab901d65798" }
# this needs to be at parity with the crosvm submodule third_party/minijail
minijail = { git = "https://chromium.googlesource.com/chromiumos/platform/minijail", rev = "fc020fd4672b3340ee706e192d043e12df8c8578" }
