git_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "mesa",
    build_file = "@//build_external/mesa:BUILD.mesa.bazel",
    commit = "875160ed32cc5bc32777fa04870a0a57ed38c987",
    remote = "https://android.googlesource.com/platform/external/mesa3d",
)
