git_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "spirv_headers",
    commit = "29981f65241605e08b0ede4cfeb999fe3b723c6a",
    remote = "https://github.com/KhronosGroup/SPIRV-Headers.git",
    patches = [
        "//build_external/spirv_headers:bazel9.patch",
    ],
    patch_strip = 1,
)
