FROM debian:stable AS base

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update -y && apt upgrade -y
RUN apt install -y devscripts config-package-dev debhelper-compat golang protobuf-compiler nasm

FROM base AS with_bazel

RUN --mount=source=.,target=/mnt,type=bind \
  /mnt/tools/buildutils/installbazel.sh

FROM with_bazel

COPY ./tools/buildutils/cw/build_package.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
