FROM debian:stable AS base

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update -y && apt upgrade -y
RUN apt install -y sudo devscripts

COPY ./tools/buildutils/installbazel.sh /installbazel.sh
RUN /installbazel.sh && rm /installbazel.sh

COPY ./tools/buildutils/build_package.sh /build_package.sh

ENTRYPOINT ["/build_package.sh"]
