# Hedron's Compile Commands Extractor for Bazel
# https://github.com/hedronvision/bazel-compile-commands-extractor
git_override(
    module_name = "hedron_compile_commands",
    # Upstream is unmaintained, see
    # https://github.com/helly25/bazel-compile-commands-extractor/blob/1f9360db1834d115c48279d38a97f30d64d3fd4a/FORK.md
    commit = "1f9360db1834d115c48279d38a97f30d64d3fd4a",
    remote = "https://github.com/helly25/bazel-compile-commands-extractor.git",
)
