name: 'Deploy docker image cuttlefish-orchestration'
inputs:
  arch:
    required: true
  deploy-channel:
    required: true
  yyyymmddhhmm:
    required: false
runs:
  using: "composite"
  steps:
  - name: Deploy docker image into Artifact Registry
    run: |
      case "${{ inputs.deploy-channel }}" in
        stable)
          # Stable version tag : X.Y.Z-<amd64|arm64>
          SEMVER=$(echo ${{ github.ref_name }} | grep -oE '[0-9]+.[0-9]+.[0-9]+')
          TAG="${SEMVER}-${{ inputs.arch }}"
          ;;
        unstable)
          # Unstable version tag : X.Y-<Github SHA 8 digit>-<amd64|arm64>
          SEMVER=$(echo ${{ github.ref_name }} | grep -oE '[0-9]+.[0-9]+')
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
          TAG="${SEMVER}-${SHORT_SHA}-${{ inputs.arch }}"
          ;;
        nightly)
          # Nightly version tag : gitYYYYMMDDHHMM-<Github SHA 8 digit>-<amd64|arm64>
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
          TAG="git${{ inputs.yyyymmddhhmm }}-${SHORT_SHA}-${{ inputs.arch }}"
          ;;
        *)
          exit 1
          ;;
      esac
      REMOTE_IMAGE_TAG=us-docker.pkg.dev/android-cuttlefish-artifacts/cuttlefish-orchestration/cuttlefish-orchestration:${TAG}

      docker tag cuttlefish-orchestration ${REMOTE_IMAGE_TAG}
      docker push ${REMOTE_IMAGE_TAG}
    shell: bash
