host/deploy/install_zip.sh /usr/bin/
host/deploy/unpack_boot_image.py /usr/lib/cuttlefish-common/bin/
host/deploy/capability_query.py /usr/lib/cuttlefish-common/bin/
host/frontend/host-orchestrator/host-orchestrator /usr/lib/cuttlefish-common/bin/
host/frontend/host-orchestrator/static /usr/share/cuttlefish-common/host-orchestrator/
host/frontend/host-orchestrator/intercept /usr/share/cuttlefish-common/host-orchestrator/
host/packages/cuttlefish-common/* /
out/generate_cert /usr/lib/cuttlefish-common/bin/
