#!/bin/bash

set -e

cd $(dirname $0)

# Override these variables to make go not depend on HOME
mkdir -p /tmp/go
export GOPATH=/tmp/go
export GOCACHE=/tmp/go/go-build

if [[ "$1" == "test" ]]; then
  go test ./...
else
 # The default action is to build
  go build -v -ldflags="-w"
fi
