load("//cuttlefish/bazel:rules.bzl", "cf_cc_binary")
load("//cuttlefish/package:rules.bzl", "package_executable", "package_files")

cf_cc_binary(
    name = "packager",
    srcs = ["packager.cc"],
    deps = [
        "//cuttlefish/common/libs/utils:files",
        "//cuttlefish/files:copy_with_attributes",
        "//cuttlefish/files:link_or_copy",
        "//cuttlefish/files:recursively_remove_directory",
        "//cuttlefish/flag_parser",
        "//cuttlefish/posix:stat",
        "//cuttlefish/posix:symlink",
        "//cuttlefish/result:expect",
        "//cuttlefish/result:result_type",
        "//libbase",
        "@abseil-cpp//absl/strings",
    ],
)

package_executable(
    name = "cvd",
    executable = "bin/cvd",
    package = ":common",
)

package_files(
    name = "common",
    base_dir = "cuttlefish-common",
    package_file_symlink_to_package_file = {
        "bin/mcopy": "bin/mtools",
        "bin/mmd": "bin/mtools",
        "bin/resize.f2fs": "bin/fsck.f2fs",
        "bin/aarch64-linux-gnu/gfxstream_graphics_detector": "bin/graphics_detector",
        "bin/aarch64-linux-gnu/libmem_overrides.so": "bin/libmem_overrides.so",
        "bin/aarch64-linux-gnu/libvk_swiftshader.so": "bin/libvk_swiftshader.so",
        "bin/x86_64-linux-gnu/gfxstream_graphics_detector": "bin/graphics_detector",
        "lib64/vulkan.lvp.so": "bin/libvk_lavapipe.so",
        "lib64/vulkan.pastel.so": "bin/libvk_swiftshader.so",
        "bin/prebuilts/libgfxstream_backend.so": "bin/libgfxstream_backend.so",
        "bin/prebuilts/crosvm": "bin/crosvm",
    },
    package_file_to_src = {
        "bin/adb": "//adb:adb",
        "bin/adb_connector": "//cuttlefish/host/frontend/adb_connector",
        "bin/assemble_cvd": "//cuttlefish/host/commands/assemble_cvd",
        "bin/avbtool.py": "@avb//:avbtool.py",
        "bin/casimir_control_server": "//cuttlefish/host/commands/casimir_control_server",
        "bin/casimir": "@casimir",
        "bin/cf_vhost_user_input": "//cuttlefish/host/commands/vhost_user_input:cf_vhost_user_input",
        "bin/console_forwarder": "//cuttlefish/host/commands/console_forwarder",
        "bin/control_env_proxy_server": "//cuttlefish/host/commands/control_env_proxy_server",
        "bin/cpio": "@libarchive//cpio:cpio",
        "bin/crosvm": "//build_external/crosvm:crosvm_bin_opt",
        "bin/cuttlefish_example_action_server": "//cuttlefish/host/example_custom_actions:cuttlefish_example_action_server",
        "bin/cvd": "//cuttlefish/host/commands/cvd",
        "bin/cvd_import_locations": "//cuttlefish/host/commands/cvd_import_locations",
        "bin/cvd_internal_display": "//cuttlefish/host/commands/display:cvd_internal_display",
        "bin/cvd_internal_env": "//cuttlefish/host/commands/cvd_env:cvd_internal_env",
        "bin/cvd_internal_host_bugreport": "//cuttlefish/host/commands/host_bugreport:cvd_internal_host_bugreport",
        "bin/cvd_internal_start": "//cuttlefish/host/commands/start:cvd_internal_start",
        "bin/cvd_internal_status": "//cuttlefish/host/commands/status:cvd_internal_status",
        "bin/cvd_internal_stop": "//cuttlefish/host/commands/stop:cvd_internal_stop",
        "bin/cvd_refresh_groups": "//cuttlefish/host/commands/refresh_groups:cvd_refresh_groups",
        "bin/cvd_send_id_disclosure": "//cuttlefish/host/commands/cvd_send_id_disclosure",
        "bin/cvd_send_sms": "//cuttlefish/host/commands/cvd_send_sms",
        "bin/cvd_update_location": "//cuttlefish/host/commands/cvd_update_location",
        "bin/cvd_update_security_algorithm": "//cuttlefish/host/commands/cvd_update_security_algorithm",
        "bin/cvdalloc": "//cuttlefish/host/commands/cvdalloc",
        "bin/e2fsck": "@e2fsprogs//:e2fsck",
        "bin/e2fsdroid": "@e2fsprogs//:e2fsdroid",
        "bin/echo_server": "//cuttlefish/host/commands/echo_server",
        "bin/extract-ikconfig": "//cuttlefish/host/commands/extract_ikconfig:extract-ikconfig.sh",
        "bin/extract-vmlinux": "//cuttlefish/host/commands/extract_vmlinux:extract-vmlinux.sh",
        "bin/fsck.f2fs": "@f2fs_tools//:fsck.f2fs",
        "bin/fastboot": "//fastboot",
        "bin/fec": "//fec",
        "bin/generate_shader_embed": "//cuttlefish/host/graphics_detector/shaders:generate_shader_embed",
        "bin/gnss_grpc_proxy": "//cuttlefish/host/commands/gnss_grpc_proxy",
        "bin/graphics_detector": "//cuttlefish/host/graphics_detector",
        "bin/health": "//cuttlefish/host/commands/health",
        "bin/kernel_log_monitor": "//cuttlefish/host/commands/kernel_log_monitor",
        "bin/libmem_overrides.so": "//cuttlefish/host/graphics/mem_overrides:libmem_overrides.so",
        "bin/libgfxstream_backend.so": "@gfxstream//host:gfxstream_backend",
        "bin/libvk_lavapipe.so": "@mesa//:vk_lavapipe",
        "bin/libvk_swiftshader.so": "@swiftshader//:vk_swiftshader",
        "bin/log_tee": "//cuttlefish/host/commands/log_tee",
        "bin/logcat_receiver": "//cuttlefish/host/commands/logcat_receiver",
        "bin/lpadd": "@android_system_extras//:lpadd",
        "bin/lpmake": "@android_system_extras//:lpmake",
        "bin/lz4": "@lz4//programs:lz4",
        "bin/make_f2fs": "@f2fs_tools//:make_f2fs",
        "bin/mkbootfs": "//mkbootfs",
        "bin/mkbootimg.py": "@mkbootimg//:mkbootimg.py",
        "bin/mke2fs": "@e2fsprogs//:mke2fs",
        "bin/mke2fs.conf": "//libext4_utils:mke2fs.conf",
        "bin/mkenvimage_slim": "//cuttlefish/host/commands/mkenvimage_slim",
        "bin/mkfs.fat": "@dosfstools//:mkfs.fat",
        "bin/mkuserimg_mke2fs.py": "//libext4_utils:mkuserimg_mke2fs.py",
        "bin/modem_simulator": "//cuttlefish/host/commands/modem_simulator",
        "bin/ms-tpm-20-ref": "@ms-tpm-20-ref//:simulator",
        "bin/mtools": "@mtools//:mtools",
        "bin/netsim": "@android_tools_netsim//:netsim",
        "bin/netsimd": "@android_tools_netsim//:netsimd",
        "bin/openwrt_control_server": "//cuttlefish/host/commands/openwrt_control_server",
        "bin/operator_proxy": "//cuttlefish/host/frontend/operator_proxy",
        "bin/pica": "@netsim_crates//:pica__pica",
        "bin/powerbtn_cvd": "//cuttlefish/host/commands/powerbtn_cvd",
        "bin/powerwash_cvd": "//cuttlefish/host/commands/powerwash_cvd",
        "bin/process_restarter": "//cuttlefish/host/commands/process_restarter",
        "bin/record_cvd": "//cuttlefish/host/commands/record_cvd",
        "bin/resize2fs": "@e2fsprogs//:resize2fs",
        "bin/restart_cvd": "//cuttlefish/host/commands/restart_cvd",
        "bin/rootcanal": "@rootcanal",
        "bin/run_cvd": "//cuttlefish/host/commands/run_cvd",
        "bin/screen_recording_server": "//cuttlefish/host/commands/screen_recording_server",
        "bin/secure_env": "//cuttlefish/host/commands/secure_env",  # TODO: schuffelen - make this more complete
        "bin/sefcontext_compile": "@selinux//:sefcontext_compile",
        "bin/sensors_simulator": "//cuttlefish/host/commands/sensors_simulator",
        "bin/simg2img": "@android_system_core//:simg2img",
        "bin/snapshot_util_cvd": "//cuttlefish/host/commands/snapshot_util_cvd",
        "bin/socket_vsock_proxy": "//cuttlefish/host/commands/socket_vsock_proxy",
        "bin/tcp_connector": "//cuttlefish/host/commands/tcp_connector",
        "bin/tombstone_receiver": "//cuttlefish/host/commands/tombstone_receiver",
        "bin/unpack_bootimg.py": "@mkbootimg//:unpack_bootimg.py",
        "bin/vhu_media_emulated_camera_splane": "//cuttlefish/host/commands/vhost_user_media/emulated_camera_splane",
        "bin/vhu_media_emulated_camera_mplane": "//cuttlefish/host/commands/vhost_user_media/emulated_camera_mplane",
        "bin/vhu_media_v4l2_stream_proxy": "//cuttlefish/host/commands/vhost_user_media/v4l2_stream_proxy",
        "bin/vk_lavapipe_icd.json": "//cuttlefish/host/graphics/vulkan:vk_lavapipe_icd",
        "bin/vk_swiftshader_icd.json": "//cuttlefish/host/graphics/vulkan:vk_swiftshader_icd",
        "bin/webRTC": "//cuttlefish/host/frontend/webrtc:webRTC",
        "bin/wmediumd": "@wmediumd//:wmediumd",
        "bin/wmediumd_gen_config": "@wmediumd//:wmediumd_gen_config",
        "etc/cvd_avb_testkey_rsa2048.pem": "//cuttlefish/host/commands/assemble_cvd/avb_testkey:testkey_rsa2048.pem",
        "etc/cvd_rsa2048.avbpubkey": "//cuttlefish/host/commands/assemble_cvd/avb_testkey:testkey_rsa2048.avbpubkey",
        "etc/cvd_avb_testkey_rsa4096.pem": "//cuttlefish/host/commands/assemble_cvd/avb_testkey:testkey_rsa4096.pem",
        "etc/cvd_rsa4096.avbpubkey": "//cuttlefish/host/commands/assemble_cvd/avb_testkey:testkey_rsa4096.avbpubkey",
        "etc/cvd_config/cvd_config_auto.json": "//cuttlefish/host/commands/assemble_cvd/config_json:config_auto.json",
        "etc/cvd_config/cvd_config_auto_md.json": "//cuttlefish/host/commands/assemble_cvd/config_json:config_auto_md.json",
        "etc/cvd_config/cvd_config_auto_portrait.json": "//cuttlefish/host/commands/assemble_cvd/config_json:config_auto_portrait.json",
        "etc/cvd_config/cvd_config_foldable.json": "//cuttlefish/host/commands/assemble_cvd/config_json:config_foldable.json",
        "etc/cvd_config/cvd_config_go.json": "//cuttlefish/host/commands/assemble_cvd/config_json:config_go.json",
        "etc/cvd_config/cvd_config_phone.json": "//cuttlefish/host/commands/assemble_cvd/config_json:config_phone.json",
        "etc/cvd_config/cvd_config_slim.json": "//cuttlefish/host/commands/assemble_cvd/config_json:config_slim.json",
        "etc/cvd_config/cvd_config_tablet.json": "//cuttlefish/host/commands/assemble_cvd/config_json:config_tablet.json",
        "etc/cvd_config/cvd_config_tv.json": "//cuttlefish/host/commands/assemble_cvd/config_json:config_tv.json",
        "etc/cvd_config/cvd_config_wear.json": "//cuttlefish/host/commands/assemble_cvd/config_json:config_wear.json",
        "etc/default_input_devices/keyboard.json": "//cuttlefish/host/commands/vhost_user_input:device_specs/keyboard.json",
        "etc/default_input_devices/mouse.json": "//cuttlefish/host/commands/vhost_user_input:device_specs/mouse.json",
        "etc/default_input_devices/gamepad.json": "//cuttlefish/host/commands/vhost_user_input:device_specs/gamepad.json",
        "etc/default_input_devices/multi_touchpad_template.json": "//cuttlefish/host/commands/vhost_user_input:device_specs/multi_touchpad_template.json",
        "etc/default_input_devices/multi_touchscreen_template.json": "//cuttlefish/host/commands/vhost_user_input:device_specs/multi_touchscreen_template.json",
        "etc/default_input_devices/rotary_wheel.json": "//cuttlefish/host/commands/vhost_user_input:device_specs/rotary_wheel.json",
        "etc/default_input_devices/single_touchpad_template.json": "//cuttlefish/host/commands/vhost_user_input:device_specs/single_touchpad_template.json",
        "etc/default_input_devices/single_touchscreen_template.json": "//cuttlefish/host/commands/vhost_user_input:device_specs/single_touchscreen_template.json",
        "etc/default_input_devices/switches.json": "//cuttlefish/host/commands/vhost_user_input:device_specs/switches.json",
        "etc/cvd_custom_action_config/cuttlefish_example_action_config.json": "//cuttlefish/host/example_custom_actions:custom_action_config.json",
        "etc/modem_simulator/files/iccprofile_for_sim0_for_CtsCarrierApiTestCases.xml": "//cuttlefish/host/commands/modem_simulator:etc/files/iccprofile_for_sim0_for_CtsCarrierApiTestCases.xml",
        "etc/modem_simulator/files/iccprofile_for_sim0.xml": "//cuttlefish/host/commands/modem_simulator:etc/files/iccprofile_for_sim0.xml",
        "etc/modem_simulator/files/iccprofile_for_sim1_for_CtsCarrierApiTestCases.xml": "//cuttlefish/host/commands/modem_simulator:etc/files/iccprofile_for_sim1_for_CtsCarrierApiTestCases.xml",
        "etc/modem_simulator/files/iccprofile_for_sim1.xml": "//cuttlefish/host/commands/modem_simulator:etc/files/iccprofile_for_sim1.xml",
        "etc/modem_simulator/files/numeric_operator.xml": "//cuttlefish/host/commands/modem_simulator:etc/files/numeric_operator.xml",
        "usr/share/webrtc/assets/client.html": "//cuttlefish/host/frontend/webrtc/html_client:client.html",
        "usr/share/webrtc/assets/controls.css": "//cuttlefish/host/frontend/webrtc/html_client:controls.css",
        "usr/share/webrtc/assets/custom.css": "//cuttlefish/host/frontend/webrtc/html_client:custom.css",
        "usr/share/webrtc/assets/style.css": "//cuttlefish/host/frontend/webrtc/html_client:style.css",
        "usr/share/webrtc/assets/js/adb.js": "//cuttlefish/host/frontend/webrtc/html_client:js/adb.js",
        "usr/share/webrtc/assets/js/app.js": "//cuttlefish/host/frontend/webrtc/html_client:js/app.js",
        "usr/share/webrtc/assets/js/cf_webrtc.js": "//cuttlefish/host/frontend/webrtc/html_client:js/cf_webrtc.js",
        "usr/share/webrtc/assets/js/controls.js": "//cuttlefish/host/frontend/webrtc/html_client:js/controls.js",
        "usr/share/webrtc/assets/js/keyboard.js": "//cuttlefish/host/frontend/webrtc/html_client:js/keyboard.js",
        "usr/share/webrtc/assets/js/location.js": "//cuttlefish/host/frontend/webrtc/html_client:js/location.js",
        "usr/share/webrtc/assets/js/mouse.js": "//cuttlefish/host/frontend/webrtc/html_client:js/mouse.js",
        "usr/share/webrtc/assets/js/gamepad.js": "//cuttlefish/host/frontend/webrtc/html_client:js/gamepad.js",
        "usr/share/webrtc/assets/js/rootcanal.js": "//cuttlefish/host/frontend/webrtc/html_client:js/rootcanal.js",
        "usr/share/webrtc/assets/js/touch.js": "//cuttlefish/host/frontend/webrtc/html_client:js/touch.js",
    },
    visibility = ["//:android_cuttlefish"],
)

package_files(
    name = "defaults",
    base_dir = "cuttlefish-integration",
    package_file_to_src = {
        "bin/cf_defaults": "//cuttlefish/host/commands/defaults:cf_defaults",
    },
    visibility = ["//:android_cuttlefish"],
)

package_files(
    name = "metrics",
    base_dir = "cuttlefish-metrics",
    package_file_to_src = {
        "bin/metrics_transmitter": "//cuttlefish/metrics/metrics_transmitter:metrics_transmitter",
    },
    visibility = ["//:android_cuttlefish"],
)
