load("//cuttlefish/bazel:rules.bzl", "cf_build_test", "cf_cc_binary")

package(
    default_visibility = ["//:android_cuttlefish"],
)

cf_build_test(name = "stop_build_test")

cf_cc_binary(
    name = "cvd_internal_stop",
    srcs = ["main.cc"],
    deps = [
        "//cuttlefish/common/libs/fs",
        "//cuttlefish/common/libs/utils:environment",
        "//cuttlefish/common/libs/utils:tee_logging",
        "//cuttlefish/files:directory_exists",
        "//cuttlefish/files:recursively_remove_directory",
        "//cuttlefish/flag_parser",
        "//cuttlefish/host/libs/command_util",
        "//cuttlefish/host/libs/config:cuttlefish_config",
        "//cuttlefish/posix:strerror",
        "//cuttlefish/result",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/strings",
    ],
)
