load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "macros",
    hdrs = ["include/android-base/macros.h"],
    strip_include_prefix = "include",
)

cc_library(
    name = "parsebool",
    srcs = ["parsebool.cpp"],
    hdrs = ["include/android-base/parsebool.h"],
    strip_include_prefix = "include",
)
