load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "collections",
    hdrs = ["include/android-base/collections.h"],
    strip_include_prefix = "include",
)

cc_library(
    name = "errno_restorer",
    hdrs = ["include/android-base/errno_restorer.h"],
    strip_include_prefix = "include",
)

cc_library(
    name = "macros",
    hdrs = ["include/android-base/macros.h"],
    strip_include_prefix = "include",
)

cc_library(
    name = "parsebool",
    srcs = ["parsebool.cpp"],
    hdrs = ["include/android-base/parsebool.h"],
    strip_include_prefix = "include",
)

cc_library(
    name = "parseint",
    hdrs = ["include/android-base/parseint.h"],
    strip_include_prefix = "include",
)

cc_library(
    name = "properties",
    srcs = ["properties.cpp"],
    hdrs = ["include/android-base/properties.h"],
    strip_include_prefix = "include",
    deps = [
        ":parsebool",
        ":parseint",
        ":strings",
        ":thread_annotations",
    ],
)

cc_library(
    name = "stringprintf",
    srcs = ["stringprintf.cpp"],
    hdrs = ["include/android-base/stringprintf.h"],
    strip_include_prefix = "include",
)

cc_library(
    name = "strings",
    srcs = ["strings.cpp"],
    hdrs = ["include/android-base/strings.h"],
    cxxopts = ["-std=c++20"],
    strip_include_prefix = "include",
    deps = [":stringprintf"],
)

cc_library(
    name = "thread_annotations",
    hdrs = ["include/android-base/thread_annotations.h"],
    strip_include_prefix = "include",
)

cc_library(
    name = "threads",
    srcs = ["threads.cpp"],
    hdrs = ["include/android-base/threads.h"],
    strip_include_prefix = "include",
)

cc_library(
    name = "unique_fd",
    hdrs = ["include/android-base/unique_fd.h"],
    strip_include_prefix = "include",
)
