#!/bin/sh

DEBIAN_DISTRIBUTION="$(lsb_release -c -s)"
DEBIAN_DOWNLOAD_URL_DEFAULT="https://cloud.debian.org/images/cloud/${DEBIAN_DISTRIBUTION}/latest"
DEBIAN_DOWNLOAD_FILE_DEFAULT="debian-13-generic-arm64.raw"

: ${DEBIAN_DOWNLOAD_URL:=$DEBIAN_DOWNLOAD_URL_DEFAULT}
: ${DEBIAN_DOWNLOAD_FILE:=$DEBIAN_DOWNLOAD_FILE_DEFAULT}

wget -nv -c "${DEBIAN_DOWNLOAD_URL}/${DEBIAN_DOWNLOAD_FILE}"
