name: 'Deploy debian packages for Cuttlefish host'
inputs:
  path:
    required: true
runs:
  using: "composite"
  steps:
  - name: 'Set up Cloud SDK'
    uses: 'google-github-actions/setup-gcloud@v3.0.0'
    with:
      version: '>= 363.0.0'
  - name: Deploy deb packages into Artifact Registry
    run: |
      pushd ${{ inputs.path }}
      for var in base user orchestration; do
        gcloud --project=android-cuttlefish-artifacts \
          artifacts apt upload \
          android-cuttlefish-nightly \
          --location=us \
          --source=$(find . -name cuttlefish-${var}_*.deb)
      done
      popd
    shell: bash
