cc_library(
    name = "shm",
    hdrs = [
        "base.h",
        "circqueue.h",
        "e2e_test_region.h",
        "graphics.h",
        "version.h",
    ],
    visibility = ["//visibility:public"],
)
