load("boot_tests.bzl", "launch_cvd_boot_test")

launch_cvd_boot_test(
  name="aosp_main_x64_phone",
  branch="aosp-main",
  target="aosp_cf_x86_64_phone-trunk_staging-userdebug"
)

launch_cvd_boot_test(
  name="aosp_android14_phone",
  branch="aosp-android14-gsi",
  target="aosp_cf_x86_64_phone-userdebug"
)

launch_cvd_boot_test(
  name="aosp_android13_phone",
  branch="aosp-android13-gsi",
  target="aosp_cf_x86_64_phone-userdebug"
)

launch_cvd_boot_test(
  name="aosp_android12_phone",
  branch="aosp-android12-gsi",
  target="aosp_cf_x86_64_phone-userdebug"
)

launch_cvd_boot_test(
  name="aosp_android11_phone",
  branch="aosp-android11-gsi",
  target="aosp_cf_x86_64_phone-userdebug"
)

launch_cvd_boot_test(
  name="aosp_android10_phone",
  branch="aosp-android10-gsi",
  target="aosp_cf_x86_64_phone-userdebug"
)

