load("cvd_boot_test.bzl", "cvd_boot_test")

cvd_boot_test(
  name="aosp_main_x64_phone",
  branch="aosp-main",
  target="aosp_cf_x86_64_phone-trunk_staging-userdebug"
)

# Not until we have credentials to download this
# cvd_boot_test(
  # name="git_main_x64_phone",
  # branch="git_main",
  # target="cf_x86_64_phone-trunk_staging-userdebug"
# )

