name: 'Build debian packages for Cuttlefish host'
inputs:
  deploy-channel:
    required: false
runs:
  using: "composite"
  steps:
  - name: Modify version for unstable/nightly channel
    if: inputs.deploy-channel != 'stable'
    run: |
      # Modify debian/changelog to build debian package with desired version
      # format.
      # Stable version format           : X.Y.Z
      # Unstable/nightly version format : X.Y.Z~gitYYYYMMDDHHMM.<Github SHA 8 digit>
      DATETIME=$(date -d '${{ github.event.repository.pushed_at }}' -u +'%Y%m%d%H%M')
      SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
      SUFFIX="~git${DATETIME}.${SHORT_SHA}"
      sed -i "1s/(\([0-9]\+.[0-9]\+.[0-9]\+\))/(\1${SUFFIX})/g" \
        base/debian/changelog
      sed -i "1s/(\([0-9]\+.[0-9]\+.[0-9]\+\))/(\1${SUFFIX})/g" \
        frontend/debian/changelog
    shell: bash
  - name: Build CF debian packages
    run: |
      sudo docker build --file "tools/buildutils/cw/Containerfile" --tag "android-cuttlefish-build" .
      sudo docker run -v=$PWD:/mnt/build -w /mnt/build -v=$HOME/bazel-disk-cache:/root/bazel-disk-cache android-cuttlefish-build base -d /root/bazel-disk-cache
      sudo docker run -v=$PWD:/mnt/build -w /mnt/build android-cuttlefish-build frontend
    shell: bash
