name: 'Build debian packages for Cuttlefish host'
inputs:
  deploy-channel:
    required: false
  yyyymmddhhmm:
    required: false
runs:
  using: "composite"
  steps:
  - name: Modify version format
    if: inputs.deploy-channel != ''
    run: |
      case "${{ inputs.deploy-channel }}" in
        stable)
          # Stable version format : X.Y.Z
          SEMVER=$(echo ${{ github.ref_name }} | grep -oE '[0-9]+.[0-9]+.[0-9]+')
          sed -i "1s/(\([0-9]\+.[0-9]\+.[0-9]\+\))/(${SEMVER})/g" \
            base/debian/changelog
          sed -i "1s/(\([0-9]\+.[0-9]\+.[0-9]\+\))/(${SEMVER})/g" \
            frontend/debian/changelog
          ;;
        unstable|nightly)
          # Unstable/nightly version format : X.Y.Z~gitYYYYMMDDHHMM.<Github SHA 8 digit>
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
          SUFFIX="~git${{ inputs.yyyymmddhhmm }}.${SHORT_SHA}"
          sed -i "1s/(\([0-9]\+.[0-9]\+.[0-9]\+\))/(\1${SUFFIX})/g" \
            base/debian/changelog
          sed -i "1s/(\([0-9]\+.[0-9]\+.[0-9]\+\))/(\1${SUFFIX})/g" \
            frontend/debian/changelog
          ;;
        *)
          exit 1
          ;;
      esac
    shell: bash
  - name: Build CF debian packages
    run: |
      sudo docker build --file "tools/buildutils/cw/Containerfile" --tag "android-cuttlefish-build" .
      sudo docker run -v=$PWD:/mnt/build -w /mnt/build -v=$HOME/bazel-disk-cache:/root/bazel-disk-cache android-cuttlefish-build base -d /root/bazel-disk-cache
      sudo docker run -v=$PWD:/mnt/build -w /mnt/build android-cuttlefish-build frontend
    shell: bash
