load("//cuttlefish/bazel:rules.bzl", "cf_build_test", "cf_cc_library", "cf_cc_test")

package(
    default_visibility = ["//:android_cuttlefish"],
)

cf_build_test(name = "fs_build_test")

cf_cc_library(
    name = "epoll",
    srcs = ["epoll.cpp"],
    hdrs = ["epoll.h"],
    include_cleaner_enabled = False,
    target_compatible_with = [
        "@platforms//os:linux",
    ],
    deps = [
        "//cuttlefish/common/libs/fs",
        "//cuttlefish/result",
    ],
)

cf_cc_library(
    name = "file_instance",
    srcs = ["file_instance.cc"],
    hdrs = ["file_instance.h"],
    include_cleaner_enabled = False,
    deps = [
        "//cuttlefish/common/libs/fs:scoped_mmap",
        "//cuttlefish/io",
        "//cuttlefish/posix:strerror",
        "//cuttlefish/result:expect",
        "//cuttlefish/result:result_type",
        "//libbase",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
    ],
)

cf_cc_library(
    name = "fs",
    srcs = [
        "shared_buf.cc",
        "shared_fd.cpp",
    ],
    hdrs = [
        "shared_buf.h",
        "shared_fd.h",
        "shared_select.h",
    ],
    include_cleaner_enabled = False,
    linkopts = select({
        "@platforms//os:linux": ["-lrt"],
        "//conditions:default": [],
    }),
    deps = [
        "//cuttlefish/common/libs/fs:file_instance",
        "//cuttlefish/common/libs/utils:environment",
        "//cuttlefish/posix:strerror",
        "//cuttlefish/result",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@fmt",
    ],
)

cf_cc_test(
    name = "fs_test",
    srcs = ["shared_fd_test.cpp"],
    include_cleaner_enabled = False,
    deps = [
        "//cuttlefish/common/libs/fs",
    ],
)

cf_cc_library(
    name = "scoped_mmap",
    srcs = ["scoped_mmap.cc"],
    hdrs = ["scoped_mmap.h"],
)

cf_cc_library(
    name = "shared_fd_stream",
    srcs = ["shared_fd_stream.cpp"],
    hdrs = ["shared_fd_stream.h"],
    include_cleaner_enabled = False,
    deps = [
        "//cuttlefish/common/libs/fs",
    ],
)
