cc_library(
    name = "fs",
    visibility = ["//visibility:public"],
    srcs = [
        "gce_fs.cpp",
        "gce_fs.h",
        "shared_fd.cpp",
        "shared_fd.h",
        "shared_select.h",
    ],
    hdrs = [
        "gce_fs.h",
        "shared_fd.h",
        "shared_select.h",
    ],
    deps = [
        "//common/libs/auto_resources",
    ],
)

