load("@rules_cc//cc:cc_library.bzl", "cc_library")

load("//:build_variables.bzl", "COPTS")

package(
    default_visibility = [
        "//:android_cuttlefish",
        "@android_system_core//:__subpackages__",
        "@android_system_extras//:__subpackages__",
        "@e2fsprogs//:__subpackages__",
        "@f2fs_tools//:__subpackages__",
        "@wmediumd//:__subpackages__",
    ],
)

cc_library(
    name = "libbase",
    deps = [
        "@android_system_libbase//:collections",
        "@android_system_libbase//:endian",
        "@android_system_libbase//:errno_restorer",
        "@android_system_libbase//:errors",
        "@android_system_libbase//:expected",
        "@android_system_libbase//:file_logging",
        "@android_system_libbase//:format",
        "@android_system_libbase//:macros",
        "@android_system_libbase//:mapped_file",
        "@android_system_libbase//:no_destructor",
        "@android_system_libbase//:off64_t",
        "@android_system_libbase//:parsebool",
        "@android_system_libbase//:parseint",
        "@android_system_libbase//:parsenetaddress",
        "@android_system_libbase//:properties",
        "@android_system_libbase//:result",
        "@android_system_libbase//:stringprintf",
        "@android_system_libbase//:strings",
        "@android_system_libbase//:thread_annotations",
        "@android_system_libbase//:threads",
        "@android_system_libbase//:unique_fd",
        "@fmt",
    ],
)
