// Copyright (C) 2023 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: control_env_proxy.proto

package operator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallUnaryMethodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName        string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	MethodName         string `protobuf:"bytes,2,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	TextFormattedProto string `protobuf:"bytes,3,opt,name=text_formatted_proto,json=textFormattedProto,proto3" json:"text_formatted_proto,omitempty"`
}

func (x *CallUnaryMethodRequest) Reset() {
	*x = CallUnaryMethodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_env_proxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallUnaryMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallUnaryMethodRequest) ProtoMessage() {}

func (x *CallUnaryMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_env_proxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallUnaryMethodRequest.ProtoReflect.Descriptor instead.
func (*CallUnaryMethodRequest) Descriptor() ([]byte, []int) {
	return file_control_env_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *CallUnaryMethodRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CallUnaryMethodRequest) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *CallUnaryMethodRequest) GetTextFormattedProto() string {
	if x != nil {
		return x.TextFormattedProto
	}
	return ""
}

type CallUnaryMethodReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TextFormattedProto string `protobuf:"bytes,1,opt,name=text_formatted_proto,json=textFormattedProto,proto3" json:"text_formatted_proto,omitempty"`
}

func (x *CallUnaryMethodReply) Reset() {
	*x = CallUnaryMethodReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_env_proxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallUnaryMethodReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallUnaryMethodReply) ProtoMessage() {}

func (x *CallUnaryMethodReply) ProtoReflect() protoreflect.Message {
	mi := &file_control_env_proxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallUnaryMethodReply.ProtoReflect.Descriptor instead.
func (*CallUnaryMethodReply) Descriptor() ([]byte, []int) {
	return file_control_env_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *CallUnaryMethodReply) GetTextFormattedProto() string {
	if x != nil {
		return x.TextFormattedProto
	}
	return ""
}

var File_control_env_proxy_proto protoreflect.FileDescriptor

var file_control_env_proxy_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x65, 0x6e, 0x76, 0x5f, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x65, 0x6e, 0x76, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x22, 0x8e, 0x01, 0x0a, 0x16, 0x43, 0x61, 0x6c, 0x6c, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x30, 0x0a, 0x14, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65,
	0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x74,
	0x65, 0x78, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x48, 0x0a, 0x14, 0x43, 0x61, 0x6c, 0x6c, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x30, 0x0a, 0x14, 0x74, 0x65, 0x78,
	0x74, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x74, 0x65, 0x78, 0x74, 0x46, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x74, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x89, 0x01, 0x0a, 0x16,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x45, 0x6e, 0x76, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6f, 0x0a, 0x0f, 0x43, 0x61, 0x6c, 0x6c, 0x55, 0x6e,
	0x61, 0x72, 0x79, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x2d, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x65, 0x6e, 0x76, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x65, 0x6e, 0x76, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x6c, 0x69, 0x62, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_control_env_proxy_proto_rawDescOnce sync.Once
	file_control_env_proxy_proto_rawDescData = file_control_env_proxy_proto_rawDesc
)

func file_control_env_proxy_proto_rawDescGZIP() []byte {
	file_control_env_proxy_proto_rawDescOnce.Do(func() {
		file_control_env_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_control_env_proxy_proto_rawDescData)
	})
	return file_control_env_proxy_proto_rawDescData
}

var file_control_env_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_control_env_proxy_proto_goTypes = []interface{}{
	(*CallUnaryMethodRequest)(nil), // 0: controlenvproxyserver.CallUnaryMethodRequest
	(*CallUnaryMethodReply)(nil),   // 1: controlenvproxyserver.CallUnaryMethodReply
}
var file_control_env_proxy_proto_depIdxs = []int32{
	0, // 0: controlenvproxyserver.ControlEnvProxyService.CallUnaryMethod:input_type -> controlenvproxyserver.CallUnaryMethodRequest
	1, // 1: controlenvproxyserver.ControlEnvProxyService.CallUnaryMethod:output_type -> controlenvproxyserver.CallUnaryMethodReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_control_env_proxy_proto_init() }
func file_control_env_proxy_proto_init() {
	if File_control_env_proxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_control_env_proxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallUnaryMethodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_env_proxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallUnaryMethodReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_control_env_proxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_env_proxy_proto_goTypes,
		DependencyIndexes: file_control_env_proxy_proto_depIdxs,
		MessageInfos:      file_control_env_proxy_proto_msgTypes,
	}.Build()
	File_control_env_proxy_proto = out.File
	file_control_env_proxy_proto_rawDesc = nil
	file_control_env_proxy_proto_goTypes = nil
	file_control_env_proxy_proto_depIdxs = nil
}
