name: Reusable Container Metadata Job

on:
  workflow_call:
    secrets:
      token:
        required: true
    inputs:
      registry:
        default: 'ghcr.io'
        required: false
        type: string
      username:
        default: ${{ GITHUB.ACTOR }}
        required: false
        type: string

    outputs:
      metadata:
        value: ${{ jobs.metadata-combined.outputs }}
        description: "Metadata output"

jobs:

  metadata:
    runs-on: ubuntu-latest
    # continue-on-error: true
    outputs:
      metadata: string
    strategy:
      max-parallel: 4
      matrix:
        platform: [ linux/amd64 ]
        target: [ rpm-builder, rpm-testing, rhel-integration, rhel-orchestration ]

    steps:

      - uses: actions/cache@v4
        id: cache
        with:
          path: path/to/dependencies
          key: ${{ runner.os }}-${{ hashFiles('**/metadata.json') }}

      - uses: 'docker/login-action@v3'
        # if: steps.cache.outputs.cache-hit != 'true'
        id: container-registry
        with:
          registry: ${{ INPUTS.REGISTRY }}
          username: ${{ INPUTS.USERNAME }}
          password: ${{ SECRETS.TOKEN }}

      - uses: 'docker/metadata-action@v5'
        # if: steps.cache.outputs.cache-hit != 'true'
        id: metadata
        with:
          images: ${{ INPUTS.REGISTRY }}/${{ MATRIX.TARGET }}
          tags: |
            ${{ INPUTS.REGISTRY }}/${{ MATRIX.TARGET }}/:latest
            type=sha
            
  metadata-combined:
      needs: metadata
      runs-on:  ubuntu-latest
      outputs:
        metadata: ${{ steps.append-variable.outputs.metadata }}
      steps:
        - id: append-variable
          run: |
            metadata="$(cat */metadata | jq -c --slurp .)"
            echo metadata=$metadata >> $GITHUB_OUTPUT