name: Docker Container

on:
  workflow_call:
    secrets:
      token:
        required: true
    inputs:
      docker-image:
        required: true
        type: string
    outputs:
      build:
        value: ${{ jobs.docker-run.outputs.build }}
        description: "Build output"
      test:
        value: ${{ jobs.docker-run.outputs.test }}
        description: "Test output"

jobs:

  docker-run:
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.copy-rpm-packages.outputs.result }}
      test: ${{ steps.test-rpm-packages.outputs.result }}

    steps:

      # https://github.com/docker/login-action
      - name: Log in to the Container registry
        id: container-registry
        uses: 'docker/login-action@v3'
        with:
          registry: ghcr.io
          username: ${{ GITHUB.ACTOR }}
          password: ${{ SECRETS.TOKEN }}

      # https://docs.docker.com/reference/cli/docker/container/run/
      # https://docs.docker.com/reference/cli/docker/container/cp/
      - name: Build RPM packages and copy these to RUNNER.TEMP
        if: ${{ ! contains(INPUTS.DOCKER-IMAGE, 'test') }}
        id: build-rpm-packages
        # --entrypoint ${{ INPUTS.ENTRY-POINT }} cannot be changed with GitHub docker.
        run: |
          docker run --name rpm-build --quiet --attach STDOUT --attach STDERR ${{ INPUTS.DOCKER-IMAGE }}
          # docker inspect -f {{.Mounts}} $CID
          CID=`docker ps -aqf "name=^rpm-build$"`
          echo "CID: ${CID}"
          docker cp $CID:/root/android-cuttlefish-rpm.tar.gz ${{ RUNNER.TEMP }}
          docker cp $CID:/root/android-cuttlefish-src-rpm.tar.gz ${{ RUNNER.TEMP }}
          docker rm rpm-build
          echo "result=ok" >> $GITHUB_OUTPUT

      # https://github.com/actions/upload-artifact
      - name: Retain Artifacts (*.rpm)
        if: ${{ ! contains(INPUTS.DOCKER-IMAGE, 'test') }}
        uses: 'actions/upload-artifact@v4'
        id: retain-rpm-packages
        with:
          name: android-cuttlefish-rpm
          path: |
            ${{ RUNNER.TEMP }}/*.tar.gz
          retention-days: 14

      # https://docs.docker.com/reference/cli/docker/container/run/
      - name: Run package tests
        if: ${{ contains(INPUTS.DOCKER-IMAGE, 'test') }}
        id: test-rpm-packages
        run: |
          docker run --name rpm-testing --quiet --attach STDOUT --attach STDERR ${{ INPUTS.DOCKER-IMAGE }}
          docker rm rpm-testing
          echo "result=ok" >> $GITHUB_OUTPUT

      # https://docs.docker.com/reference/cli/docker/container/run/
      - name: Run integration tests
        if: ${{ contains(INPUTS.DOCKER-IMAGE, 'integration') }}
        id: test-integration
        run: |
          docker run --name rhel-integration --quiet --attach STDOUT --attach STDERR ${{ INPUTS.DOCKER-IMAGE }}
          echo "result=ok" >> $GITHUB_OUTPUT

      # https://docs.docker.com/reference/cli/docker/container/run/
      - name: Run orchestration test
        if: ${{ contains(INPUTS.DOCKER-IMAGE, 'orchestration') }}
        id: test-orchestration
        run: |
          docker run --name rhel-integration --quiet --attach STDOUT --attach STDERR ${{ INPUTS.DOCKER-IMAGE }}
          echo "result=ok" >> $GITHUB_OUTPUT