name: Docker Container

on:
  workflow_call:
    secrets:
      token:
        required: true
    inputs:
      docker-image:
        required: true
        type: string
      entry-point:
        required: false
        type: string
        default: '/root/buildscript.sh'
    outputs:
      container:
        value: ${{ jobs.docker-run.outputs.container }}
        description: "Container ID"
      build:
        value: ${{ jobs.docker-run.outputs.build }}
        description: "Build output"
      test:
        value: ${{ jobs.docker-run.outputs.test }}
        description: "Test output"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    if: ${{ contains(INPUTS.ENTRY-POINT, 'build') }}

    container:
      image: ${{ INPUTS.DOCKER-IMAGE }}
      options: '--cpus 1'
      credentials:
        username: ${{ GITHUB.ACTOR }}
        password: ${{ SECRETS.TOKEN }}
      volumes:
        - /home/runner

    outputs:
      build: ${{ steps.copy-rpm-packages.outputs.result }}
      test: ${{ steps.test-rpm-packages.outputs.result }}

    steps:

      # https://docs.docker.com/reference/cli/docker/container/cp/
      - name: Copy from container to file-system /tmp
        if: ${{ contains(INPUTS.ENTRY-POINT, 'build') }}
        id: copy-rpm-packages
        run: |
          CID='' && echo `docker ps --format '{{.ID}}'` >> $CID
          docker exec $CID ${{ INPUTS.ENTRY-POINT }}
          docker cp $CID:/root/${{ GITHUB.REPOSITORY }}/tools/rpmbuild/RPMS/* ${{ GITHUB.WORKSPACE }}
          docker cp $CID:/root/${{ GITHUB.REPOSITORY }}/tools/rpmbuild/SRPMS/* ${{ GITHUB.WORKSPACE }}
          echo "result=ok" >> $GITHUB_OUTPUT

      # https://github.com/actions/upload-artifact
      - name: Retain Artifacts (*.rpm)
        if: ${{ contains(INPUTS.ENTRY-POINT, 'build') }}
        uses: 'actions/upload-artifact@v4'
        id: retain-rpm
        with:
          name: ${{ GITHUB.REPOSITORY }}-rpm
          path: |
            ${{ GITHUB.WORKSPACE }}/*.rpm
          retention-days: 14

      # https://github.com/actions/upload-artifact
      - name: Retain Artifacts (*.srpm)
        if: ${{ contains(INPUTS.ENTRY-POINT, 'build') }}
        uses: 'actions/upload-artifact@v4'
        id: retain-srpm
        with:
          name: ${{ ENV.REPO_NAME }}-srpm
          path: |
            ${{ GITHUB.REPOSITORY }}/*.srpm
          retention-days: 14

      # https://docs.docker.com/reference/cli/docker/container/cp/
      - name: Copy from container to file-system /tmp
        if: ${{ contains(INPUTS.ENTRY-POINT, 'test') }}
        id: test-rpm-packages
        run: |
          sudo ${{ INPUTS.ENTRY-POINT }}
          echo "result=ok" >> $GITHUB_OUTPUT

  docker-test:
    if: ${{ contains(INPUTS.ENTRY-POINT, 'test') }}
    runs-on: ubuntu-latest
    needs: docker-build
    container:
      image: ${{ INPUTS.DOCKER-IMAGE }}
      options: '--cpus 1'
      credentials:
        username: ${{ GITHUB.ACTOR }}
        password: ${{ SECRETS.TOKEN }}
      volumes:
        - /home/runner

    outputs:
      test: ${{ steps.test-rpm-packages.outputs.result }}

    steps:

      # https://docs.docker.com/reference/cli/docker/container/cp/
      - name: Copy from container to file-system /tmp
        id: test-rpm-packages
        run: |
          CID='' && echo `docker ps --format '{{.ID}}'` >> $CID
          docker exec $CID ${{ INPUTS.ENTRY-POINT }}
          echo "result=ok" >> $GITHUB_OUTPUT
