name: Docker Container

on:
  workflow_call:
    secrets:
      token:
        required: true
    inputs:
      docker-image:
        required: true
        type: string
    outputs:
      build:
        value: ${{ jobs.docker-run.outputs.build }}
        description: "Build output"
      test:
        value: ${{ jobs.docker-run.outputs.test }}
        description: "Test output"

jobs:

  docker-run:
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.copy-rpm-packages.outputs.result }}
      test: ${{ steps.test-rpm-packages.outputs.result }}

    steps:

      # https://github.com/docker/login-action
      - name: Log in to the Container registry
        id: container-registry
        uses: 'docker/login-action@v3'
        with:
          registry: ghcr.io
          username: ${{ GITHUB.ACTOR }}
          password: ${{ SECRETS.TOKEN }}

      # https://docs.docker.com/reference/cli/docker/container/run/
      # https://docs.docker.com/reference/cli/docker/container/cp/
      - name: Run the build script and copy packages to workspace
        if: ${{ ! contains(INPUTS.DOCKER-IMAGE, 'test') }}
        id: build-rpm-packages
        # --entrypoint ${{ INPUTS.ENTRY-POINT }} cannot be changed with GitHub docker.
        run: |
          docker run --name rpm-build --attach STDOUT --attach STDERR --quiet ${{ INPUTS.DOCKER-IMAGE }}
          # docker inspect -f {{.Mounts}} $CID 
          CID=`docker ps -aqf "name=^rpm-build$"`
          echo "CID: ${CID}"
          docker cp $CID:/root/android-cuttlefish/tools/rpmbuild/RPMS/ ${{ RUNNER.TEMP }}/
          docker cp $CID:/root/android-cuttlefish/tools/rpmbuild/SRPMS/ ${{ RUNNER.TEMP }}/
          docker rm rpm-build
          echo "result=ok" >> $GITHUB_OUTPUT

      # https://github.com/actions/upload-artifact
      - name: Retain Artifacts (*.rpm)
        if: ${{ ! contains(INPUTS.DOCKER-IMAGE, 'test') }}
        uses: 'actions/upload-artifact@v4'
        id: retain-rpm-packages
        with:
          name: ${{ GITHUB.REPOSITORY }}-rpm
          path: |
            {{ GITHUB.WORKSPACE }}/packages/*.rpm
          retention-days: 14

      # https://github.com/actions/upload-artifact
      - name: Retain Artifacts (*.src.rpm)
        if: ${{ ! contains(INPUTS.DOCKER-IMAGE, 'test') }}
        uses: 'actions/upload-artifact@v4'
        id: retain-srpm-packages
        with:
          name: ${{ ENV.REPO_NAME }}-src-rpm
          path: |
            ${{ RUNNER.TEMP }}/*.src.rpm
          retention-days: 14

      # https://docs.docker.com/reference/cli/docker/container/run/
      - name: Run the test script
        if: ${{ contains(INPUTS.DOCKER-IMAGE, 'test') }}
        id: test-rpm-packages
        # --entrypoint ${{ INPUTS.ENTRY-POINT }} cannot be changed with GitHub docker.
        run: |
          docker run --name rpm-test --attach STDOUT --attach STDERR --quiet ${{ INPUTS.DOCKER-IMAGE }}
          CID=`docker ps -aqf "name=^rpm-test"`
          echo "CID: ${CID}"
          docker rm rpm-test
          echo "result=ok" >> $GITHUB_OUTPUT
