name: Docker Container

on:
  workflow_call:
    inputs:
      docker-image:
        required: true
        type: string
      entry-point:
        required: false
        type: string
        default: '/root/buildscript.sh'

jobs:
  docker-run:
    runs-on: ubuntu-latest
    container:
      image: 'docker://${{ INPUTS.DOCKER_IMAGE }}'
      volumes:
        - /home/runner
      credentials:
        username: ${{ GITHUB.ACTOR }}
        password: ${{ SECRETS.GITHUB_TOKEN }}

    steps:

      # https://docs.docker.com/reference/cli/docker/container/cp/
      - name: Copy from container to file-system /tmp
        run: |
          docker cp CONTAINER:/home/runner/android-cuttlefish/tools/rpmbuild/RPMS/* ${{ GITHUB.WORKSPACE }}
          docker cp CONTAINER:/home/runner/android-cuttlefish/tools/rpmbuild/SRPMS/* ${{ GITHUB.WORKSPACE }}

      # https://github.com/actions/upload-artifact
      - name: Retain Artifacts (*.rpm)
        id: retain-rpm
        uses: 'actions/upload-artifact@v4'
        with:
          name: android-cuttlefish-rpm
          path: |
            ${{ GITHUB.WORKSPACE }}/*.rpm
          retention-days: 14

      # https://github.com/actions/upload-artifact
      - name: Retain Artifacts (*.srpm)
        id: retain-srpm
        uses: 'actions/upload-artifact@v4'
        with:
          name: android-cuttlefish-srpm
          path: |
            ${{ GITHUB.WORKSPACE }}/*.srpm
          retention-days: 14
