name: Docker Container

on:
  workflow_call:
    secrets:
      token:
        required: true
    inputs:
      docker-image:
        required: true
        type: string
      entry-point:
        required: false
        type: string
        default: '/root/buildscript.sh'
    outputs:
      container: ${{ jobs.docker-run.outputs.container }}
      build: ${{ jobs.docker-run.outputs.build }}
      test: ${{ jobs.docker-run.outputs.test }}

jobs:
  docker-run:
    runs-on: ubuntu-latest
    container:
      image: ${{ INPUTS.DOCKER_IMAGE }}
      options: '--cpus 1'
      credentials:
        username: ${{ GITHUB.ACTOR }}
        password: ${{ SECRETS.TOKEN }}
      volumes:
        - /home/runner
    outputs:
      container: ${{ steps.container-id.outputs.result }}
      build: ${{ steps.copy-rpm-packages.outputs.result }}
      test: ${{ steps.test-rpm-packages.outputs.result }}
    steps:
      - name: Container ID
        id: container-id
        run: echo "result=`docker ps --format '{{.ID}}'`" >> $GITHUB_OUTPUT

      # https://docs.docker.com/reference/cli/docker/container/cp/
      - name: Copy from container to file-system /tmp
        if: ${{ contains(INPUTS.ENTRY_POINT, 'build') }}
        id: copy-rpm-packages
        run: |
          ${{ INPUTS.ENTRY_POINT }}
          docker cp $CID:/root/android-cuttlefish/tools/rpmbuild/RPMS/* ${{ GITHUB.WORKSPACE }}
          docker cp $CID:/root/android-cuttlefish/tools/rpmbuild/SRPMS/* ${{ GITHUB.WORKSPACE }}
          echo "result=ok" >> $GITHUB_OUTPUT

      # https://github.com/actions/upload-artifact
      - name: Retain Artifacts (*.rpm)
        if: ${{ contains(INPUTS.ENTRY_POINT, 'build') }}
        uses: 'actions/upload-artifact@v4'
        id: retain-rpm
        with:
          name: android-cuttlefish-rpm
          path: |
            ${{ GITHUB.WORKSPACE }}/*.rpm
          retention-days: 14

      # https://github.com/actions/upload-artifact
      - name: Retain Artifacts (*.srpm)
        if: ${{ contains(INPUTS.ENTRY_POINT, 'build') }}
        uses: 'actions/upload-artifact@v4'
        id: retain-srpm
        with:
          name: android-cuttlefish-srpm
          path: |
            ${{ GITHUB.WORKSPACE }}/*.srpm
          retention-days: 14

      # https://docs.docker.com/reference/cli/docker/container/cp/
      - name: Copy from container to file-system /tmp
        if: ${{ contains(INPUTS.ENTRY_POINT, 'test') }}
        id: test-rpm-packages
        run: |
          ${{ INPUTS.ENTRY_POINT }}
          echo "result=ok" >> $GITHUB_OUTPUT
