name: Reusable Docker Container Run

on:
  workflow_call:
    secrets:
      token:
        description: 'GitHub auth token'
        required: true
      # TODO: This might be the signature required.
      # https://dl.google.com/linux/linux_signing_key.pub
      pgp_signature:
        description: 'PGP signature for signing RPM'
        required: false
      pgp_passphrase:
        description: 'Passphrase for PGP signature'
        required: false
    inputs:
      platform:
        description: 'The platform to build for'
        default: linux/amd64
        required: false
        type: string
      registry:
        description: 'Docker registry hostname'
        default: 'ghcr.io'
        required: false
        type: string
      username:
        description: 'Docker registry username'
        required: true
        type: string
      image:
        description: 'Docker image name'
        required: true
        type: string
      tag:
        description: 'Docker image tag'
        default: latest
        required: false
        type: string
      repository:
        description: 'GitHub repository'
        default: android-cuttlefish
        required: true
        type: string
      branch:
        description: 'GitHub branch'
        default: main
        required: false
        type: string
      runner:
        description: 'GitHub runner image label'
        default: ${{ VARS.RUNNER_86 }}
        required: false
        type: string
      runner_gid:
        description: 'GitHub runner GID'
        default: 118
        required: false
        type: string
      runner_uid:
        description: 'GitHub runner UIG'
        default: 118
        required: false
        type: string
jobs:

  docker-run:
    runs-on: ${{ INPUTS.RUNNER }}
    env:
      DOCKER_IMAGE: ${{ INPUTS.REGISTRY }}/${{ INPUTS.USERNAME }}/${{ INPUTS.IMAGE }}:${{ INPUTS.TAG }}
      DOCKER_OPTIONS: '--name ${{ INPUTS.IMAGE }} --platform ${{ INPUTS.PLATFORM }} --attach STDERR --attach STDOUT --quiet'
      ENV_VARS: '--env REPO_USER="${{ INPUTS.USERNAME }}" --env REPO_NAME="${{ INPUTS.REPOSITORY }}" --env REPO_BRANCH="${{ INPUTS.BRANCH }}" --env RUNNER_UID="${{ INPUTS.RUNNER_UID }}" --env RUNNER_GID="${{ INPUTS.RUNNER_GID }}"'
    steps:

      - shell: bash
        id: setup
        run: |
          PLATFORM='${{ INPUTS.PLATFORM }}'
          ARTIFACT_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}-rhel9-${PLATFORM#linux/}-unsigned
          echo "CACHE_PATH=${{ RUNNER.TEMP }}/.cache" >> $GITHUB_OUTPUT
          echo "ARTIFACT_PATH=${{ RUNNER.TEMP }}/.rpms" >> $GITHUB_OUTPUT
          echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT
          echo "::group::Setup Info"
          echo "::notice file=reusable-docker.yml,line={83},title=Artifact Name: ${ARTIFACT_NAME}"
          echo "::endgroup::"

      # https://github.com/docker/login-action
      - name: Log in to the Container registry
        uses: 'docker/login-action@v3'
        id: container-registry
        with:
          registry: ${{ INPUTS.REGISTRY }}
          username: ${{ INPUTS.USERNAME }}
          password: ${{ SECRETS.TOKEN }}

      # Need to check out once again, in order to utilize `hashFiles()`.
      - uses: 'actions/checkout@v4'
      - name: Restore Bazel cache
        id: bazel-cache-restore
        uses: 'actions/cache/restore@v4'
        with:
          key: bazel-cache-${{ RUNNER.ARCH }}-${{ hashFiles('./base/cvd/**.bazel') }}
          restore-keys: bazel-cache-${{ RUNNER.ARCH }}-
          path: ${{ STEPS.SETUP.OUTPUTS.CACHE_PATH }}

      # https://docs.docker.com/reference/cli/docker/container/run/
      # https://docs.docker.com/reference/cli/docker/container/cp/
      # --entrypoint ${{ INPUTS.ENTRY-POINT }} cannot be changed with GitHub docker.
      - name: Run image ${{ INPUTS.REGISTRY }}/${{ INPUTS.USERNAME }}/${{ INPUTS.IMAGE }} with source https://github.com/${{ INPUTS.USERNAME }}/${{ INPUTS.REPOSITORY }}.git#${{ INPUTS.BRANCH }}
        id: build-rpm-packages
        shell: bash
        env:
          VOLUMES: '--volume ${{ RUNNER.TEMP }}/.cache:/home/runner/.cache --volume ${{ RUNNER.TEMP }}/.rpms:/home/runner/.rpms'
        run: |
          mkdir -p ${{ STEPS.SETUP.OUTPUTS.ARTIFACT_PATH }}
          mkdir -p ${{ STEPS.SETUP.OUTPUTS.CACHE_PATH }}
          docker run $DOCKER_OPTIONS $VOLUMES $ENV_VARS $DOCKER_IMAGE

      # https://github.com/actions/upload-artifact
      - name: Retain Artifacts (*.rpm)
        uses: 'actions/upload-artifact@v4'
        if: ${{ success() }}
        id: retain-rpm-packages
        with:
          name: ${{ STEPS.SETUP.OUTPUTS.ARTIFACT_NAME }}
          path: ${{ STEPS.SETUP.OUTPUTS.ARTIFACT_PATH }}
          include-hidden-files: 'true'
          retention-days: 14

      - name: List directory ${{ STEPS.SETUP.OUTPUTS.ARTIFACT_PATH }}
        id: list-rpm-packages
        shell: bash
        run: |
          if [ "$(ls -1 ${{ STEPS.SETUP.OUTPUTS.ARTIFACT_PATH }}/*.rpm 2>/dev/null | wc -l)" -lt 4 ]; then
            echo "::warning file=reusable-docker.yml,line=134,title=RPM Build::Less than the expected 4 RPM packages were built."
            # for FILE in ${{ STEPS.SETUP.OUTPUTS.ARTIFACT_PATH }}/*.rpm; do echo "::notice file=reusable-docker.yml,line=136,title=${FILE}"; done
          fi
          echo "Ubuntu mount-point: ${{ STEPS.SETUP.OUTPUTS.ARTIFACT_PATH }}"
          ls -la ${{ STEPS.SETUP.OUTPUTS.ARTIFACT_PATH }}
          ls -lan ${{ STEPS.SETUP.OUTPUTS.ARTIFACT_PATH }}

      # https://github.com/actions/cache
      - name: Save Bazel cache
        id: bazel-cache-save
        uses: 'actions/cache/save@v4'
        with:
          key: ${{ steps.bazel-cache-restore.outputs.cache-primary-key }}
          path: ${{ STEPS.SETUP.OUTPUTS.CACHE_PATH }}
