name: Reusable Container Metadata Job

on:
  workflow_call:
    secrets:
      token:
        required: true
    inputs:
      registry:
        default: 'ghcr.io'
        required: false
        type: string
      username:
        default: ${{ GITHUB.ACTOR }}
        required: false
        type: string

    outputs:
      metadata:
        value: ${{ jobs.metadata.outputs }}
        description: "Metadata output"

jobs:

  metadata:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        platform: [ linux/amd64 ]
        target: [ rpm-builder, rpm-testing, rhel-integration, rhel-orchestration ]

    steps:

      - uses: 'docker/login-action@v3'
        id: container-registry
        with:
          registry: ${{ INPUTS.REGISTRY }}
          username: ${{ INPUTS.USERNAME }}
          password: ${{ SECRETS.TOKEN }}

      - uses: 'docker/metadata-action@v5'
        id: metadata
        with:
          images: ${{ INPUTS.REGISTRY }}/${{ INPUTS.IMAGE }}
          tags: |
            ${{ INPUTS.IMAGE }}:latest
            type=sha
