name: Docker Container

on:
  workflow_call:
    inputs:
      docker-image:
        required: true
        type: string
      entry-point:
        required: false
        type: string
        default: '/root/buildscript.sh'
    secrets:
      token:
        required: true

jobs:
  docker-run:
    runs-on: ubuntu-latest
    container:
      image: ${{ INPUTS.DOCKER_IMAGE }}
      # https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/running-jobs-in-a-container#setting-container-resource-options
      options: '--cpus 1 --entrypoint ${{ INPUTS.ENTRY_POINT }}'
      volumes:
        - /home/runner
      credentials:
        username: ${{ GITHUB.ACTOR }}
        password: ${{ SECRETS.TOKEN }}

    steps:

      # https://docs.docker.com/reference/cli/docker/container/cp/
      - name: Copy from container to file-system /tmp
        run: |
          export CID=`docker ps --format '{{.ID}}'`
          docker cp $CID:/root/android-cuttlefish/tools/rpmbuild/RPMS/* ${{ GITHUB.WORKSPACE }}
          docker cp $CID:/root/android-cuttlefish/tools/rpmbuild/SRPMS/* ${{ GITHUB.WORKSPACE }}

      # https://github.com/actions/upload-artifact
      - name: Retain Artifacts (*.rpm)
        if: ${{ INPUTS.ENTRY_POINT == '/root/buildscript.sh' }}
        id: retain-rpm
        uses: 'actions/upload-artifact@v4'
        with:
          name: android-cuttlefish-rpm
          path: |
            ${{ GITHUB.WORKSPACE }}/*.rpm
          retention-days: 14

      # https://github.com/actions/upload-artifact
      - name: Retain Artifacts (*.srpm)
        if: ${{ INPUTS.ENTRY_POINT == '/root/buildscript.sh' }}
        id: retain-srpm
        uses: 'actions/upload-artifact@v4'
        with:
          name: android-cuttlefish-srpm
          path: |
            ${{ GITHUB.WORKSPACE }}/*.srpm
          retention-days: 14
