name: ReusableBuild 

on:
  pull_request:

jobs:
  build-arm64-cuttlefish-deb-job:
    runs-on: ubuntu-22.04-arm
    steps:
    - name: checkout repository
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # aka v2
    - name: Build CF debian packages
      run: |
        sudo docker build --file "tools/buildutils/cw/Containerfile" --tag "android-cuttlefish-build" .
        sudo docker run -v=$PWD:/mnt/build -w /mnt/build android-cuttlefish-build base
        sudo docker run -v=$PWD:/mnt/build -w /mnt/build android-cuttlefish-build frontend
    - name: Build debs.tar
      run: find . -name 'cuttlefish-*.deb' -print0 | tar -cvf debs.tar --null --files-from -
    - name: Publish debs.tar
      uses: actions/upload-artifact@v4
      with:
        name: debs
        path: debs.tar
    - name: Check status
      run: df -h
