name: Docker Container

on:
  workflow_call:
    secrets:
      token:
        required: true
    inputs:
      docker-image:
        required: true
        type: string
      entry-point:
        required: false
        type: string
        default: '/root/buildscript.sh'
    outputs:
      container:
        value: ${{ jobs.docker-run.outputs.container }}
        description: "Container ID"
      build:
        value: ${{ jobs.docker-run.outputs.build }}
        description: "Build output"
      test:
        value: ${{ jobs.docker-run.outputs.test }}
        description: "Test output"

jobs:
  docker-run:
    runs-on: ubuntu-latest
    if: ${{ contains(INPUTS.ENTRY-POINT, 'build') }}

    container:
      image: ${{ INPUTS.DOCKER-IMAGE }}
      options: '--cpus 1'
      credentials:
        username: ${{ GITHUB.ACTOR }}
        password: ${{ SECRETS.TOKEN }}
      volumes:
        - /home/runner
      ports:
        - 1080 1443
        - 2080 2443
        - 8443 15550-15560
        - 6520-6620

    outputs:
      build: ${{ steps.copy-rpm-packages.outputs.result }}
      test: ${{ steps.test-rpm-packages.outputs.result }}

    steps:

      # https://docs.docker.com/reference/cli/docker/container/cp/
      - name: Run the build script and copy packages to workspace
        if: ${{ contains(INPUTS.ENTRY-POINT, 'build') }}
        id: build-rpm-packages
        run: |
          CID=$(basename $(cat /proc/1/cpuset))
          echo "Container ID: $CID"
          ls -la
          ${{ INPUTS.ENTRY-POINT }}
          cp /root/${{ GITHUB.REPOSITORY }}/tools/rpmbuild/RPMS/* ${{ GITHUB.WORKSPACE }}
          cp /root/${{ GITHUB.REPOSITORY }}/tools/rpmbuild/SRPMS/* ${{ GITHUB.WORKSPACE }}
          echo "result=ok" >> $GITHUB_OUTPUT

      # https://github.com/actions/upload-artifact
      - name: Retain Artifacts (*.rpm)
        if: ${{ contains(INPUTS.ENTRY-POINT, 'build') }}
        uses: 'actions/upload-artifact@v4'
        id: retain-rpm-packages
        with:
          name: ${{ GITHUB.REPOSITORY }}-rpm
          path: |
            ${{ GITHUB.WORKSPACE }}/*.rpm
          retention-days: 14

      # https://github.com/actions/upload-artifact
      - name: Retain Artifacts (*.srpm)
        if: ${{ contains(INPUTS.ENTRY-POINT, 'build') }}
        uses: 'actions/upload-artifact@v4'
        id: retain-srpm-packages
        with:
          name: ${{ ENV.REPO_NAME }}-srpm
          path: |
            ${{ GITHUB.REPOSITORY }}/*.srpm
          retention-days: 14

      # https://docs.docker.com/reference/cli/docker/container/cp/
      - name: Run the test script
        if: ${{ contains(INPUTS.ENTRY-POINT, 'test') }}
        id: test-rpm-packages
        run: |
          ${{ INPUTS.ENTRY-POINT }}
          echo "result=ok" >> $GITHUB_OUTPUT