name: RPM Builder

on: [ workflow_call ]

jobs:

  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      max-parallel: 2
      matrix:
        platform: [ linux/amd64, linux/arm64/v8 ]
        target: [ rpm-builder ]
        include:
          - target: rpm-builder
            runner: ubuntu-latest
            platform: linux/amd64
            dirname: x86_64
          - target: rpm-builder
            runner: ubuntu-24.04-arm
            platform: linux/arm64/v8
            dirname: arm64

    steps:
      - uses: 'actions/checkout@v4'

      - uses: 'docker/login-action@v3'
        id: container-registry
        with:
          registry: 'ghcr.io'
          username: ${{ GITHUB.ACTOR }}
          password: ${{ SECRETS.GITHUB_TOKEN }}

      # https://github.com/docker/metadata-action
      - name: Extract metadata (tags, labels)
        uses: 'docker/metadata-action@v5'
        id: metadata
        with:
          images: ghcr.io/${{ GITHUB.ACTOR }}/${{ MATRIX.TARGET }}
          tags: |
            type=sha
            latest

      # https://github.com/marketplace/actions/build-and-push-docker-images
      - uses: 'docker/setup-buildx-action@v3'
      - uses: 'docker/setup-qemu-action@v3'
        with:
          platforms: arm64

      - name: Build and push Docker image
        uses: 'docker/build-push-action@v6'
        id: build
        with:
          context: .
          file: docker/rpm-builder/${{ MATRIX.DIRNAME }}/Dockerfile
          push: ${{ GITHUB.EVENT_NAME != 'pull_request' }}
          platforms: ${{ MATRIX.PLATFORM }}
          labels: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}

      # Note: The digest comes from `buildx`, not the metadata.
      # https://github.com/actions/attest-build-provenance
      - name: Generate artifact attestation
        uses: 'actions/attest-build-provenance@v2'
        with:
          subject-name: ghcr.io/${{ GITHUB.ACTOR }}/${{ MATRIX.TARGET }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true

  run-image:
    uses: ./.github/workflows/reusable-docker.yml
    needs: build-image
    with:
      registry: 'ghcr.io'
      username: ${{ GITHUB.ACTOR }}
      image: ${{ MATRIX.TARGET }}
      platform: ${{ MATRIX.PLATFORM }}
    secrets:
      token: ${{ SECRETS.GITHUB_TOKEN }}
    strategy:
      max-parallel: 2
      matrix:
        platform: [ linux/amd64, linux/arm64 ]
        target: [ rpm-builder ]
        include:
          - target: rpm-builder
            runner: ubuntu-latest
            platform: linux/amd64
            dirname: x86_64
          - target: rpm-builder
            runner: ubuntu-24.04-arm
            platform: linux/arm64/v8
            dirname: arm64
