name: Update Bazel Cache

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'

jobs:
  update-cvd-test-bazel-cache:
    if: ${{ github.repository_owner == 'google' }}
    runs-on: ubuntu-24.04
    steps:
    - name: Free disk space
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        large-packages: false
        swap-storage: false
    - name: Checkout repository
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # aka v2
    - name: Mount bazel cache
      uses: ./.github/actions/mount-bazel-cache
      with:
        action-name: "run-cvd-unit-tests"
        cache-path: "$HOME/bazel-disk-cache"
        writable: "true"
    - name: Run cvd unit tests
      uses: ./.github/actions/run-cvd-unit-tests
      with:
        cache-path: "$HOME/bazel-disk-cache"
  update-debian-package-x86-bazel-cache:
    if: ${{ github.repository_owner == 'google' }}
    runs-on: ubuntu-22.04
    steps:
    - name: Free disk space
      uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # aka v1.3.1
      with:
        docker-images: false
        swap-storage: false
    - name: checkout repository
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # aka v2
    - name: Mount bazel cache
      uses: ./.github/actions/mount-bazel-cache
      with:
        action-name: "build-debian-packages"
        cache-path: "$HOME/bazel-disk-cache"
        writable: "true"
    - name: Build CF host debian packages
      uses: ./.github/actions/build-debian-packages
      with:
        cache-path: "$HOME/bazel-disk-cache"
  update-debian-package-arm-bazel-cache:
    if: ${{ github.repository_owner == 'google' }}
    runs-on: ubuntu-22.04-arm
    steps:
    - name: Free disk space
      uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # aka v1.3.1
      with:
        docker-images: false
        swap-storage: false
    - name: checkout repository
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # aka v2
    - name: Mount bazel cache
      uses: ./.github/actions/mount-bazel-cache
      with:
        action-name: "build-debian-packages"
        cache-path: "$HOME/bazel-disk-cache"
        writable: "true"
    - name: Build CF host debian packages
      uses: ./.github/actions/build-debian-packages
      with:
        cache-path: "$HOME/bazel-disk-cache"
