name: Update Bazel Cache

on:
  pull_request:
  push:
    branches-ignore:
      - main  # push events to main branch occur after PRs are merged, when the same checks were run

jobs:
  update-bazel-cache-debian-package:
    runs-on: ubuntu-22.04-4core
    container:
      image: debian@sha256:823849b88ae7e9b6ceb605fbdf51566499c234a9cfca8da1e4f22234fd65a09c # debian:bullseye-20250317 (amd64)
    steps:
    - name: Check for dockerenv file
      run: (ls /.dockerenv && echo 'Found dockerenv') || (echo 'No dockerenv')
    - name: setup apt
      run: apt update -y && apt upgrade -y
    - name: install debuild dependencies
      run: apt install -y git devscripts config-package-dev debhelper-compat golang protobuf-compiler nasm
    - name: go version
      run: go version
    - name: checkout repository
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # aka v2
      with:
        path: "android-cuttlefish"
    - name: install bazel
      run: bash android-cuttlefish/tools/buildutils/installbazel.sh
    - name: install package build dependencies
      run: cd android-cuttlefish/base && mk-build-deps -i -t 'apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y'
    - name: Mount Bazel cache
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: ${{ runner.os }}-${{ runner.arch }}-bazel-debian-package-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-bazel-debian-package-${{ github.ref_name }}-
          ${{ runner.os }}-${{ runner.arch }}-bazel-debian-package-main-
          ${{ runner.os }}-${{ runner.arch }}-bazel-debian-package-
    - name: build base debian package
      run: cd android-cuttlefish/base && debuild -i -us -uc -b
  update-bazel-cache-cvd-unit-tests:
    runs-on: ubuntu-22.04-4core
    container:
      image: debian@sha256:9258a75a7e4323c9e5562b361effc84ee747920116d8adfc98a465a5cdc9150e # debian:bookworm-20250407 (amd64)
    steps:
    - name: Checkout repository
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # aka v2
    - name: Setup apt
      run: apt update -y && apt upgrade -y
    - name: Install dependencies
      run: apt install -y git clang libcurl4-openssl-dev clang-tidy libtinfo5 xxd cmake liblzma-dev libvpx-dev libopus-dev libaom-dev autoconf libtool nasm
    - name: Install bazel
      run: bash tools/buildutils/installbazel.sh
    - name: Mount Bazel cache
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: ${{ runner.os }}-${{ runner.arch }}-bazel-cvd-test-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-bazel-cvd-test-${{ github.ref_name }}-
          ${{ runner.os }}-${{ runner.arch }}-bazel-cvd-test-main-
          ${{ runner.os }}-${{ runner.arch }}-bazel-cvd-test-
    - name: build base debian package
      run: cd android-cuttlefish/base && debuild -i -us -uc -b
    - name: Run unit tests
      run: cd base/cvd && bazel test --sandbox_writable_path=$HOME --test_output=errors ...

