name: Update Bazel Cache

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'

jobs:
  update-cvd-test-bazel-cache:
    if: ${{ github.repository_owner == 'google' }}
    runs-on: ubuntu-24.04
    steps:
    - name: Free disk space
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        large-packages: false
        swap-storage: false
    - name: Checkout repository
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # aka v2
    - name: Load cache config
      run: |
        cat .config/cache-config.env >> $GITHUB_ENV
        echo "JOB_HASH=$(yq . .github/actions/run-cvd-unit-tests/action.yaml | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - name: Generate cache key prefix
      run: echo "CACHE_KEY_PREFIX=${{ runner.os }}-${{ runner.arch }}-bazel-disk-cache-${{ env.CACHE_VERSION }}-unit-test-${{ env.JOB_HASH }}" >> $GITHUB_ENV
    - name: Mount Bazel cache
      uses: actions/cache@v4
      with:
        path: "~/bazel-disk-cache"
        key: ${{ format('{0}-{1}-{2}-{3}', env.CACHE_KEY_PREFIX, github.ref_name, github.sha, github.event_name) }}
        restore-keys: |
          ${{ github.event_name == 'push' && format('{0}-{1}-', env.CACHE_KEY_PREFIX, github.ref_name) || '' }}
          ${{ github.event_name == 'push' && format('{0}-main-', env.CACHE_KEY_PREFIX) || '' }}
          ${{ github.event_name == 'push' && format('{0}-', env.CACHE_KEY_PREFIX) || '' }}
    - name: Run cvd unit tests
      uses: ./.github/actions/run-cvd-unit-tests
      with:
        cache-path: "$HOME/bazel-disk-cache"
  update-debian-package-x86-bazel-cache:
    if: ${{ github.repository_owner == 'google' }}
    runs-on: ubuntu-22.04
    steps:
    - name: Free disk space
      uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # aka v1.3.1
      with:
        docker-images: false
        swap-storage: false
    - name: checkout repository
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # aka v2
    - name: Load cache config
      run: |
        cat .config/cache-config.env >> $GITHUB_ENV
        echo "JOB_HASH=$(yq .jobs[\"build-debian-package-x86\"] .github/workflows/presubmit.yaml | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - name: Generate cache key prefix
      run: echo "CACHE_KEY_PREFIX=${{ runner.os }}-${{ runner.arch }}-bazel-disk-cache-${{ env.CACHE_VERSION }}-debian-package-${{ env.JOB_HASH }}" >> $GITHUB_ENV
    - name: Mount Bazel cache
      uses: actions/cache@v4
      with:
        path: "~/bazel-disk-cache"
        key: ${{ format('{0}-{1}-{2}-{3}', env.CACHE_KEY_PREFIX, github.ref_name, github.sha, github.event_name) }}
        restore-keys: |
          ${{ github.event_name == 'push' && format('{0}-{1}-', env.CACHE_KEY_PREFIX, github.ref_name) || '' }}
          ${{ github.event_name == 'push' && format('{0}-main-', env.CACHE_KEY_PREFIX) || '' }}
          ${{ github.event_name == 'push' && format('{0}-', env.CACHE_KEY_PREFIX) || '' }}
    - name: Build CF debian packages
      run: |
        sudo docker build --file "tools/buildutils/cw/Containerfile" --tag "android-cuttlefish-build" .
        sudo docker run -v=$PWD:/mnt/build -w /mnt/build -v=$HOME/bazel-disk-cache:/root/bazel-disk-cache android-cuttlefish-build base -d /root/bazel-disk-cache
  update-debian-package-arm-bazel-cache:
    if: ${{ github.repository_owner == 'google' }}
    runs-on: ubuntu-22.04-arm
    steps:
    - name: Free disk space
      uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # aka v1.3.1
      with:
        docker-images: false
        swap-storage: false
    - name: checkout repository
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # aka v2
    - name: Load cache config
      run: |
        cat .config/cache-config.env >> $GITHUB_ENV
        echo "JOB_HASH=$(yq .jobs[\"build-debian-package-arm\"] .github/workflows/presubmit.yaml | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - name: Generate cache key prefix
      run: echo "CACHE_KEY_PREFIX=${{ runner.os }}-${{ runner.arch }}-bazel-disk-cache-${{ env.CACHE_VERSION }}-debian-package-${{ env.JOB_HASH }}" >> $GITHUB_ENV
    - name: Mount Bazel cache
      uses: actions/cache@v4
      with:
        path: "~/bazel-disk-cache"
        key: ${{ format('{0}-{1}-{2}-{3}', env.CACHE_KEY_PREFIX, github.ref_name, github.sha, github.event_name) }}
        restore-keys: |
          ${{ github.event_name == 'push' && format('{0}-{1}-', env.CACHE_KEY_PREFIX, github.ref_name) || '' }}
          ${{ github.event_name == 'push' && format('{0}-main-', env.CACHE_KEY_PREFIX) || '' }}
          ${{ github.event_name == 'push' && format('{0}-', env.CACHE_KEY_PREFIX) || '' }}
    - name: Build CF debian packages
      run: |
        sudo docker build --file "tools/buildutils/cw/Containerfile" --tag "android-cuttlefish-build" .
        sudo docker run -v=$PWD:/mnt/build -w /mnt/build -v=$HOME/bazel-disk-cache:/root/bazel-disk-cache android-cuttlefish-build base -d /root/bazel-disk-cache
