load("//cuttlefish/bazel:rules.bzl", "cf_build_test", "cf_cc_binary")

package(
    default_visibility = ["//:android_cuttlefish"],
)

cf_build_test(name = "log_tee_build_test")

cf_cc_binary(
    name = "log_tee",
    srcs = ["log_tee.cpp"],
    deps = [
        "//cuttlefish/common/libs/fs",
        "//cuttlefish/common/libs/utils:tee_logging",
        "//cuttlefish/host/libs/config:cuttlefish_config",
        "//cuttlefish/posix:strerror",
        "//cuttlefish/result:result_type",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/strings",
        "@gflags",
    ],
)
